Feature/search api 20191120
connect-foundation/2019-10 pull request #101
Opened 2019-11-29 01:21 UTC by KimJye

## 작업 내용
검색 API를 작성했습니다.
검색어를 입력하면 영상, 사용자, 태그가 각각 검색이 됩니다.
모두탭에서는 5개씩 보여줍니다.
더보기 또는 영상, 사용자, 태그에서는 검색된 결과에대해 페이지네이션한 결과를 보여줍니다. 

검색은 인기순으로 정렬됩니다.
영상은 인기도순, 생성순, id순으로 정렬됩니다.
사용자는 비디오를 업로드한 개수 순, 생성된순, id순으로 정렬됩니다.
태그는 태그된 비디오가 많은 순, 생성된순, id순으로 정렬됩니다.

## 실행 방법
검색된 영상의 전체 API: http://localhost:4000/videos?page=1&keyword=너무나
검색된 영상의 개수가 5개일때: http://localhost:4000/tags?keyword=java&limit=5

검색된 사용자의 전체 API: http://localhost:4000/users?keyword=루비&page=1
검색된 사용자의 개수가 5개일때: http://localhost:4000/users?keyword=루비&limit=5

검색된 태그의 전체 API: http://localhost:4000/tags?keyword=java&page=1
검색된 태그의 개수가 5개일때: http://localhost:4000/tags?keyword=java&limit=5

## 결과 첨부

2019-12-01 12:20 UTC, Atercatus requested changes

2019-12-01 12:20 UTC, Atercatus commented on packages/server/src/common/pipes/get-videos.pipe/index.ts
>  const defaultValue: VideosQueryDto = {
생성자를 이용하는게 더 좋을 거 같습니다.

2019-12-01 12:20 UTC, Atercatus commented on packages/server/src/common/pipes/get-videos.pipe/index.ts
> +    value.keyword = keyword;
이런 동작들도 생성자를 이용해주세요

2019-12-01 12:20 UTC, Atercatus commented on packages/server/src/video/dto/videos-query.dto.ts
>      public page: number,
DTO는 외부에서 바꿀 일이 없기 때문에 `readonly` 키워드를 써서 좀 더 안전하게 하는 게 좋을 거 같습니다.

2019-12-01 12:20 UTC, Atercatus commented on packages/server/src/video/video.service.ts
>    public async findVideos(videosQueryDto: VideosQueryDto): Promise<Video[]> {
한 함수가 너무 긴 거 같은데 분리하면 좋을 거 같습니다.

2019-12-01 12:20 UTC, Atercatus commented on packages/server/src/common/pipes/get-users.pipe/index.ts
> +const defaultValue: UsersQueryDto = {
생성자 이용해주세요

2019-12-01 12:20 UTC, Atercatus commented on packages/server/src/common/pipes/get-users.pipe/index.ts
> +    value.limit = parseInt(limit, 10);
이런 동작들도 클래스의 생성자 이용해주시면 좋을 거 같습니다.

2019-12-01 12:20 UTC, Atercatus commented on packages/server/src/user/dto/user-response.dto.ts
> +export class UserResponseDto {
이름이 다소 일반적인 거 같습니다. 좀 더 명확하면 좋을 거 같아요

2019-12-01 12:20 UTC, Atercatus commented on packages/server/src/user/user.controller.ts
> +  ): Promise<UserResponseDto[]> {
하나의 DTO로 감싸는게 좋을 거 같습니다.

2019-12-01 12:20 UTC, Atercatus commented on packages/server/src/user/user.service.ts
> +  public async findUsers(usersQueryDto: UsersQueryDto): Promise<User[]> {
한 함수의 내용이 너무 긴 거 같습니다. 여러 함수로 분리하면 가독성이 더 높아질거 같아요

2019-12-01 12:20 UTC, Atercatus commented on packages/server/src/common/pipes/get-tags.pipe/index.ts
> +    const value = defaultValue;
클래스로 뺴서 생성자 이용해주시면 좋을 거 같습니다.

2019-12-01 12:20 UTC, Atercatus commented on packages/server/src/common/pipes/get-tags.pipe/index.ts
> +    value.limit = parseInt(limit, 10);
클래스 생성자 이용해주시면 좋을 거 같습니다.

2019-12-01 12:20 UTC, Atercatus commented on packages/server/src/tag/dto/tag-response.dto.ts
> +export class TagResponseDto {
이름이 일반적이여서 관훈님이 현재 작성하시는 부분과 혼동이 올 수 있을 거 같습니다.

2019-12-01 12:20 UTC, Atercatus commented on packages/server/src/tag/dto/tags-query.dto.ts
> +export class TagsQueryDto {
이름이 일반적이여서 관훈님이 현재 작성하시는 부분과 혼동이 올 수 있을 거 같습니다.

2019-12-01 12:20 UTC, Atercatus commented on packages/server/src/tag/tag.service.ts
> +    if (limit) {
아래의 코드와 중복이 많은거 같은데 중복을 줄이고 limit에 따라 달라지는 코드만 작성이 되면 좋겠습니다.

2019-12-01 12:20 UTC, Atercatus commented on packages/server/src/common/pipes/query-string.pipe/getDto.ts
> +export class GetQueryStringPipeDto {
이름이 동사여서 이부분은 다르게 변경하기로 했습니다.

2019-12-01 12:20 UTC, Atercatus commented on packages/server/src/common/pipes/query-string.pipe/requestDto.ts
> +export class QueryStringDto {
너무 일반적이여서 수정해야 할 거 같습니다.

2019-12-01 12:20 UTC, Atercatus commented on packages/server/src/user/user.service.ts
> +    if (limit) {
함수가 다소 길고 중복되는 부분이 많은 거 같습니다. 조건식을 잘 사용하면 중복을 줄여서 가독성을 높일 수 있을 거 같습니다.

2019-12-01 12:20 UTC, Atercatus commented on packages/server/src/video/video.service.ts
> +  public async findVideos(queryStringDto: QueryStringDto): Promise<Video[]> {
함수가 다소 길고 중복이 많은거 같습니다. 중복을 줄여서 가독성을 높으면 좋을 거 같습니다.

2019-12-02 02:09 UTC, riverandeye requested changes

2019-12-02 02:09 UTC, riverandeye commented on packages/server/src/common/pipes/query-string.pipe/index.ts
> +    return limit && !isNaN(parsedLimit) && parsedLimit === 5;
제 생각엔 클라이언트에서 limit를 적절하게 요청하면 되고, 입력된 limit 값을 5로 고정할 필요는 없다고 생각합니다.

2019-12-02 02:14 UTC, riverandeye commented on packages/server/src/common/pipes/query-string.pipe/index.ts
> +    const parsedPage = parseInt(page, 10);
page=2가나다 이런식으로 넣었는데 2로 입력이 되더라구요. 
좀 더 엄밀하게 숫자만 입력되게 하고싶으면 regex를 사용하는것이 괜찮을 것 같습니다.

2019-12-02 02:14 UTC, riverandeye commented on packages/server/src/tag/tag.service.ts
> +          nameKeyword: '%' + keyword + '%',
이렇게 쓰는거군요~ :smile:

2019-12-02 02:22 UTC, KimJye commented on packages/server/src/common/pipes/query-string.pipe/index.ts
> +    return limit && !isNaN(parsedLimit) && parsedLimit === 5;
> 제 생각엔 클라이언트에서 limit를 적절하게 요청하면 되고, 입력된 limit 값을 5로 고정할 필요는 없다고 생각합니다.

검색 결과에대해서, 모두보기일때는 영상, 유저, 태그에대해 각각 무조건 최대 5개만 보여줍니다.
따라서 클라이언트에서 조절할수없게 강제하였습니다.
그래

2019-12-02 02:23 UTC, KimJye commented on packages/server/src/tag/tag.service.ts
> +          nameKeyword: '%' + keyword + '%',
추후 성능개선이 필요한 쿼리입니다..ㅠㅠ

2019-12-02 02:24 UTC, KimJye commented on packages/server/src/common/pipes/query-string.pipe/getDto.ts
> +export class GetQueryStringPipeDto {
어떻게요???

2019-12-02 02:24 UTC, KimJye commented on packages/server/src/common/pipes/query-string.pipe/requestDto.ts
> +export class QueryStringDto {
어떤 이름이 좋을까요??

2019-12-02 02:36 UTC, alexKwonIsAwesome commented on packages/server/src/common/pipes/query-string.pipe/index.ts
> +export class GetQueryStringPipe implements PipeTransform {
복수개의 리소스를 반환하는 컨트롤러에 공통적으로 사용하고 계신것 같은데, 예외 사항들도 전부 포함되어 있나요?

2019-12-02 02:36 UTC, alexKwonIsAwesome commented on packages/server/src/common/pipes/query-string.pipe/index.ts
> +    return limit && !isNaN(parsedLimit) && parsedLimit === 5;
validateLimit이 limit의 값이 반드시 존재하길 원하고 있는데, 그러면 안되지 않나요? 일반적인 경우에는 page를 활용해서 limit을 서버가 정해준 값을 활용하도록 하고 있는데, 만약 page값을 주고 limit을 안주는 정상 시나리오도 본 메소드 때문에 validation에서 실패가 발생할 것 같습니다.

2019-12-02 04:59 UTC, KimJye commented on packages/server/src/common/pipes/query-string.pipe/index.ts
> +export class GetQueryStringPipe implements PipeTransform {
네엡!!! 밑에 되어있어요옹~

2019-12-02 05:00 UTC, KimJye commented on packages/server/src/common/pipes/query-string.pipe/index.ts
> +    return limit && !isNaN(parsedLimit) && parsedLimit === 5;
> validateLimit이 limit의 값이 반드시 존재하길 원하고 있는데, 그러면 안되지 않나요? 일반적인 경우에는 page를 활용해서 limit을 서버가 정해준 값을 활용하도록 하고 있는데, 만약 page값을 주고 limit을 안주는 정상 시나리오도 본 메소드 때문에 validation에서 실패가 발생할 것 같습니다.

limit이 있을때만 본 메소드가 실행됩니다아~

2019-12-02 05:01 UTC, KimJye commented on packages/server/src/tag/dto/tag-response.dto.ts
> +export class TagResponseDto {
현재 같은 부분을 작업하고있습니다.
관훈님과 짝코딩할게요~

2019-12-02 05:04 UTC, KimJye commented on packages/server/src/user/dto/user-response.dto.ts
> +export class UserResponseDto {
이름짓기 넘나 어렵네요..

2019-12-03 08:23 UTC, closed without merging