인기 태그 UI 및 API 구현
connect-foundation/2019-10 pull request #114
Opened 2019-12-01 05:03 UTC by riverandeye

## 작업 내용

페이지네이션을 통해 태그의 목록을 가져오는 함수를 작성하였다.

## 실행 방법

실행 후 localhost:3000/tags 에 접속하여 결과를 확인한다. 

## 결과 첨부

2019-12-01 10:12 UTC, Atercatus commented
![image](https://user-images.githubusercontent.com/32104982/69912568-6b74db80-146e-11ea-9041-bbe671114f52.png)
이 부분은 일부러 이렇게 하신건가요

2019-12-01 11:01 UTC, Atercatus requested changes

2019-12-01 11:01 UTC, Atercatus commented on packages/client/libs/chunkList.ts
> +export const chunkList = (list, itemsPerChunk: number) => {
함수 이름에서 쓰인 chunk는 동사로 쓰여지고 매개변수에서 쓰이는 chunk는 명사로 쓰여지네요. 
```
export const makeChunkList = (itemList, itemsPerChunks: number) => {
  return itemList.reduce((chunkList, item, index) => {
    const curItemPosition = Math.floor(index / itemsPerChunks);

    if (!chunkList[curItemPosition]) {
      chunkList[curItemPosition] = [];
    }

    chunkList[curItemPosition].push(item);

    return chunkList;
  }, []);
};
```
이런식으로 명명을 좀 고치면 어떨까요

2019-12-01 11:01 UTC, Atercatus commented on packages/client/views/TagList/hooks.ts
> +  const [hasMore, setHasMore] = useState(true);
초기값이 true인 이유가 있나요?
더 보기 버튼을 활성화 할 것인지 아닌지 판단하는 값 같은데 처음부터 없을 가능성이 있지않나요?

2019-12-01 11:01 UTC, Atercatus commented on packages/client/views/TagList/index.tsx
> +  const numberWithCommas = (x: number) => {
함수의 이름은 동사로 해주세요

2019-12-01 11:01 UTC, Atercatus commented on packages/client/views/TagList/index.tsx
> +const getOneTag = (tag: Tag) => {
단순 탐색이 아닌 함수의 동작을 나타낼태는 get 보다는 make 등이 좋습니다.

2019-12-01 11:01 UTC, Atercatus commented on packages/client/views/TagList/index.tsx
> +              {getTagList(tags)}
`map`을 사용하셔서 반복적인 코드를 줄이신 건 굉장히 좋습니다.
다만 코드가 너무 분산되어서 전체적인 구조가 보기 힘듭니다.
제 생각이지만 react에서 뷰 담당 코드를 한곳이 아닌 다른 곳에 분산하는 것은 다소 오해를 불러 일으킬 수 있을 거 같습니다.

2019-12-01 11:01 UTC, Atercatus commented on packages/client/views/TagList/styles.tsx
> +  overflow: visible !important;
`!important`를 쓰신 이유가 있나요?

2019-12-01 11:01 UTC, Atercatus commented on packages/server/src/common/pipes/page-parser/page-parser.pipe.ts
> +  private validate(page: string) {
어떤 validation인지 알 수 있으면 좋을거 같아요

2019-12-01 11:01 UTC, Atercatus commented on packages/server/src/tag/tag.controller.ts
> +  ): Promise<TagsResponseDto[]> {
ResponseDto를 배열로 반환하시면 안됩니다.
배열을 가지고 있는 하나의 DTO로 만들어주세요
https://martinfowler.com/eaaCatalog/dataTransferObject.html 
위 글을 한번 참조해 주세요

2019-12-02 00:58 UTC, riverandeye commented on packages/client/libs/chunkList.ts
> +export const chunkList = (list, itemsPerChunk: number) => {
좋습니다~

2019-12-02 01:44 UTC, riverandeye commented on packages/client/views/TagList/hooks.ts
> +  const [hasMore, setHasMore] = useState(true);
처음부터 없다면, useQuery로 온 payload가 빈 배열을 반환하므로 payload.length >= 0이 되어 hasMore가 false로 변경됩니다.

2019-12-02 02:24 UTC, alexKwonIsAwesome commented on packages/client/views/TagList/hooks.ts
> +    if (payload) {
이러면 error가 발생할 때 payload가 에러 객체라서 런타임 에러가 날꺼에요. error 객체도 같이 검사해야합니다.

2019-12-02 02:24 UTC, alexKwonIsAwesome commented on packages/client/views/TagList/index.tsx
> +    return x.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ',');
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString
이 메소드를 사용하면 됩니다.

2019-12-02 02:24 UTC, alexKwonIsAwesome commented on packages/client/views/TagList/index.tsx
> +    <S.ContainerGrid key={index} container spacing={2} justify={'flex-start'}>
value가 string이면 justify="flex-start" 와 같이 작성해 주세요.

2019-12-02 02:24 UTC, alexKwonIsAwesome commented on packages/client/views/TagList/index.tsx
> +const getOneLineOfTags = (tags: Tag[], index: number) => {
Row를 작성하는 함수이니, makeRow라고 명명하는건 어떨까요?

2019-12-02 02:24 UTC, alexKwonIsAwesome commented on packages/client/views/TagList/styles.tsx
> +  overflow: visible !important;
이 부분은 핫리스트의 경우에는 로딩바를 중앙 정렬 하기 위해서 사용했는데, infinite scroll 라이브러리의 속성을 override하기 위해 작사용하고 있습니다.  아마 여기서도 같은 목적으로 사용되지 않았을까 싶네요.

2019-12-02 02:24 UTC, alexKwonIsAwesome commented on packages/client/libs/chunkList.ts
> +export const chunkList = (list, itemsPerChunk: number) => {
엄밀히 말하면, 평면 배열 데이터를 특정 갯수만큼 잘라서 한 개의 row에 감싸기 위한 덩어리로 변환하기 위해 사용하는 함수겠죠? Row라는 단어를 함수명에 포함하는건 어떨까요? chunkListByRow? 흠 모르겠네요

2019-12-02 02:24 UTC, alexKwonIsAwesome commented on packages/server/src/common/pipes/page-parser/page-parser.pipe.ts
> +    const numberCheckRegex = /^[0-9]*$/gm;
정규표현식이 page가 0인 경우도 valid하게 검사하는것 같은데, 저희 앱은 page 1부터 시작하는 것으로 설계되었기 때문에 수정해야 할것 같습니다. 또, 정규표현식 대신에 isNaN을 활용하는것에는 문제가 있나봐요?

2019-12-02 02:24 UTC, alexKwonIsAwesome commented on packages/server/src/tag/dto/tags-response.dto.ts
> +export class TagsResponseDto {
한 개의 태그를 반환하는 dto라면, TagResponseDto라고 명명하는게 좋지 않을까요?

2019-12-02 02:24 UTC, alexKwonIsAwesome commented on packages/server/src/tag/tag.service.ts
> +    return await this.tagRepository.find({
limit은 설정 안해도 되나요? 한 페이지당 몇개의 데이터가 반환되나요?

2019-12-02 04:12 UTC, KimJye commented on packages/server/src/tag/tag.controller.ts
> +  public async getHotTags(
태그들을 가져오는 경우가 인기순과 검색 결과가 있을텐데요
제가 구현한 태그 검색 결과들을 가져오는 함수에따르면 query를 통해서 인기순 태그들을 가져올수있습니다.
이 부분에대해서 짝코딩을 하면 어떨까요?

2019-12-02 06:06 UTC, riverandeye commented on packages/client/views/TagList/index.tsx
> +const getOneTag = (tag: Tag) => {
이거 고민했는데 좋은조언이에요~

2019-12-02 06:07 UTC, riverandeye commented on packages/client/views/TagList/index.tsx
> +              {getTagList(tags)}
맞아요 서로 다른 기능을 하는 함수로 분리를 했는데, 그 함수가 너무 많아져서 또 고민이 생기네여.

2019-12-02 10:35 UTC, riverandeye commented on packages/server/src/common/pipes/page-parser/page-parser.pipe.ts
> +  private validate(page: string) {
validateNumber로 변경하였습니다.

2019-12-02 10:43 UTC, riverandeye commented on packages/server/src/tag/tag.controller.ts
> +  ): Promise<TagsResponseDto[]> {
반영하였습니다~

2019-12-02 10:46 UTC, riverandeye commented on packages/server/src/common/pipes/page-parser/page-parser.pipe.ts
> +    const numberCheckRegex = /^[0-9]*$/gm;
https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/isNaN\
isNaN을 쓰지 않는 이유는, '0.0314E+2' 와 같은 표현도 Number로 인식을 하더라구요. 
위와 같은 경우가 URL로 입력되는 경우에서는 옳지 못하다고 생각해서 사용하지 않았습니다.

2019-12-02 10:49 UTC, riverandeye commented on packages/server/src/common/pipes/page-parser/page-parser.pipe.ts
> +    const numberCheckRegex = /^[0-9]*$/gm;
꼼꼼하고 좋은 지적입니다. Regex를 수정하여 반영하였습니다~

2019-12-02 10:50 UTC, riverandeye commented on packages/server/src/tag/dto/tags-response.dto.ts
> +export class TagsResponseDto {
좋은 지적입니다. 수정하였습니다~

2019-12-02 10:51 UTC, riverandeye commented on packages/server/src/tag/tag.service.ts
> +    return await this.tagRepository.find({
태그를 가져올 갯수에 해당하는 imit은 요청으로 처리하지 않았고, 내부 상수로 지정하였습니다.
take: TAGS_PER_PAGE 를 설정하여 한 페이지당 태그의 갯수를 지정하였습니다.
현재 지정된 기본값은 24 입니다.

2019-12-02 10:51 UTC, riverandeye commented on packages/server/src/tag/tag.controller.ts
> +  public async getHotTags(
네 좋아요~

2019-12-02 10:52 UTC, riverandeye commented on packages/client/views/TagList/index.tsx
> +    <S.ContainerGrid key={index} container spacing={2} justify={'flex-start'}>
반영하였습니다ㅎㅎ

2019-12-03 12:43 UTC, closed without merging