검색결과 화면 UI 및 라우팅
connect-foundation/2019-10 pull request #135
Opened 2019-12-06 02:25 UTC by KimJye

## 작업 내용
검색 결과 화면을 구현했습니다.
검색 결과 없음을 구현했습니다.

## 실행 방법
검색입력창에 검색어를 입력한다.
여러개의 탭을 눌러본다~

## 결과 첨부

![image](https://user-images.githubusercontent.com/33201628/70290348-eba69280-181a-11ea-8387-67a30b13b3a4.png)

![image](https://user-images.githubusercontent.com/33201628/70290360-f8c38180-181a-11ea-8de9-63f81673dfa6.png)

![결과화면없음](https://user-images.githubusercontent.com/33201628/70290310-d03b8780-181a-11ea-9d83-5aa98309becb.png)

2019-12-08 18:12 UTC, riverandeye requested changes
어려운 기능 맡으신것 같아요 고생이 많으십니다.

2019-12-08 18:12 UTC, riverandeye commented on packages/client/views/Search/index.tsx
> +              </S.NoResults>
아직 검색이 완료되지 않은 경우에도 검색결과가 없습니다... 라는 글귀가 나타나는 것으로 보입니다.
검색 기능 자체에 지장은 없으나, 사용성 측면에서 부적절해보여서 리뷰를 남깁니다.

2019-12-08 18:12 UTC, riverandeye commented on packages/client/views/Search/hooks.ts
> +
검색에 아무 값도 넣지 않는 경우에도 검색이 가능한 것으로 보입니다.
또, keyword 문자열을 trim 해서 공백을 제거해야 할 것 같이 보입니다. 
이 부분은 정말 복잡하고 어렵네요..

![image](https://user-images.githubusercontent.com/41494099/70393577-c1c5b980-1a2e-11ea-9d6a-a683791366f5.png)

2019-12-08 18:12 UTC, riverandeye commented on packages/client/views/Search/index.tsx
>  const Searched: React.FunctionComponent = () => {
Searched 라는 이름이 조금 모호한 것 같아요. 
SearchResult 는 어떠신가요?

2019-12-08 18:12 UTC, riverandeye commented on packages/client/views/Search/index.tsx
> +  const page = undefined;
const page = null 이 더 적합한 것 같습니다. undefined는 조금 명확하지 않다고 생각이 듭니다.

2019-12-09 01:10 UTC, KimJye commented on packages/client/views/Search/hooks.ts
> +
호옷~~~ 감사합니다~!

2019-12-12 04:32 UTC, hyokualexkwon reviewed
전반적으로 좋습니다.

그런데 디렉토리 구조를 저희 프로젝트에 맞게 수정해야 할 것 같습니다. 컴포넌트 디렉토리는 또다른 컴포넌트 디렉토리의 sub 디렉토리가 되지 않도록 수정해야 합니다. 전부 components로 분리해 주세요. 물론 이름도 조금 바뀌어야겠죠?

2019-12-12 04:32 UTC, alexKwonIsAwesome commented on packages/client/components/Searched/ViewMore/index.tsx
> +            <ArrowRightSVG />
화면에서는 svg의 opacity가 적용되어 있지 않네요!

2019-12-12 04:32 UTC, alexKwonIsAwesome commented on packages/client/components/Searched/Tags/index.tsx
> +              <S.Tag>{tag.name}</S.Tag>;
`;`은 지우셔야겠네요

2019-12-12 04:32 UTC, alexKwonIsAwesome commented on packages/client/views/Search/Tags/index.tsx
> +  optionMap.set('tags', '태그');
컴포넌트가 렌더링 될 때마다 Map객체를 생성하고, 다수의 set을 하게 될것 같아요. 차라리 contstants에 별도의 객체 상수로 가지고 있는게 낫지 않을까요?

2019-12-12 04:32 UTC, alexKwonIsAwesome commented on packages/client/views/Search/Tags/index.tsx
> +  const routerObject = (queryKeyword, num) => {
라우터에 사용할 객체를 만드는 함수니까, 함수명 맨 앞에는 동사를 작성해야 할 것 같습니다. 동시에 자료형인 object도 생략해도 되겠네요.

2019-12-12 04:32 UTC, alexKwonIsAwesome commented on packages/client/views/Search/Videos/index.tsx
> +    if (value === searchOptions[0].value) {
searchOption 객체가 배열로 되어있는데, 특정 항목을 index로 접근하는 코드가 가독성이 저하되는것 같아요. 배열 대신에 객체를 활용해서 특정 key를 통해 값을 접근할 수 있게 한다면 이 부분의 코드 가독성이 향상되지 않을까요?

2019-12-12 04:32 UTC, alexKwonIsAwesome commented on packages/client/views/Search/index.tsx
>  const Searched: React.FunctionComponent = () => {
디렉토리명은 Search 인데 컴포넌트 이름은 Searched네요. 통일해야 할 것 같습니다.

2019-12-12 04:32 UTC, alexKwonIsAwesome commented on packages/client/views/Search/index.tsx
> +              </S.NoResults>
로딩중에는 본 문구가 나타나지 않도록 변경해야 할 것 같습니다.

2019-12-12 04:32 UTC, alexKwonIsAwesome commented on packages/client/views/Search/index.tsx
> +                <S.Line />
구분자의 높이가 1px이 되도록 수정해 주세요. Video페이지에서 예시를 찾아볼 수 있습니다.

2019-12-12 04:32 UTC, alexKwonIsAwesome commented on packages/client/views/Search/styles.tsx
> +`;
모바일 화면에서는 양 옆의 간격이 없어야 합니다. 비디오 페이지를 참고 해 주세요.

![image](https://user-images.githubusercontent.com/17868599/70682815-640dc780-1ce3-11ea-8ec1-f6edfc360339.png)

2019-12-12 13:45 UTC, KimJye commented on packages/client/views/Search/index.tsx
> +              </S.NoResults>
시정했습니다 감사합니다

2019-12-13 06:23 UTC, Atercatus requested changes
많은 코드를 작성하신다고 고생 많으셨습니다.
중복된 코드를 줄이고 조건 변경에 예민한 조건문들을 삭제하는 것 이 좋을 거 같습니다.
또한 명확하지 않은 변수명은 가독성을 떨어트려 리뷰어에게 많은 부담이 되므로 피하시는게 좋을 거 같습니다.

2019-12-13 06:23 UTC, Atercatus commented on packages/client/components/SearchBar/index.tsx
> +        query: { keyword: e.target.value },
state 를 쓰는게 더 좋지 않을까요?

2019-12-13 06:23 UTC, Atercatus commented on packages/client/components/SearchBar/index.tsx
> +  const [value, setValue] = useState('');
value가 뭔지 알 기가 힘들어요 명확한 이름이면 좋겠어요

2019-12-13 06:23 UTC, Atercatus commented on packages/client/components/SearchedArea/index.tsx
> +  if (type === 'tags') {
문자열은 constants로 빼면 좋을 거 같습니다.

2019-12-13 06:23 UTC, Atercatus commented on packages/client/components/SearchedArea/index.tsx
> +  if (type === 'users') {
문자열은 constants로 빼면 좋을 거 같습니다.

2019-12-13 06:23 UTC, Atercatus commented on packages/client/components/SearchedArea/index.tsx
> +  if (type === 'videos') {
문자열은 constants로 빼면 좋을 거 같습니다.

2019-12-13 06:23 UTC, Atercatus commented on packages/client/components/ViewMore/index.tsx
> +const ViewMore = ({ searchKeyword, num, options }) => {
num 이라는 변수는 다른 명확한 이름을 가진 변수로 바꾸면 좋을 거 같습니다.

2019-12-13 06:23 UTC, Atercatus commented on packages/client/pages/search/index.tsx
> +export { default } from '../../views/Searched';
Searched 는 명사가 아니라서 다른 이름이면 더 좋을 거 같아요.

2019-12-13 06:23 UTC, Atercatus commented on packages/client/views/Searched/index.tsx
> +  const allCount = hasData ? videoCount + userCount + tagCount : null;
비교를 숫자랑 하시던데 `null` 보단 `0` 이 더 명확할 거 같네요.

2019-12-13 06:23 UTC, Atercatus commented on packages/client/views/Searched/index.tsx
> +    if (value === searchOptions[1].value) {
무슨 조건인지 알기가 어려워요

2019-12-13 06:23 UTC, Atercatus commented on packages/client/views/Searched/index.tsx
> +    if (value === searchOptions[1].value) {
searchOptions를 배열로 하신이유가 있나요?

2019-12-13 06:23 UTC, Atercatus commented on packages/client/views/Searched/index.tsx
> +                {videoCount > 0 && (
`vidoCount &&` 로만 하면 안되나요?

2019-12-13 06:23 UTC, Atercatus commented on packages/client/views/Searched/index.tsx
> +            {allCount === 0 && hasData ? (
무슨 조건인지 함수로 빼면 좋을 거 같습니다.

2019-12-13 06:23 UTC, Atercatus commented on packages/client/views/SearchedResults/index.tsx
> +    customSearchOptions[0] === undefined ? 'all' : customSearchOptions[0].value;
`customSearchOptions[0] ? 'all' : customSearchOptions[0].value;` 로 하지 않으신 이유가 있나요

2019-12-13 06:23 UTC, Atercatus commented on packages/client/components/SearchedResultsArea/index.tsx
> +  if (type === 'tags') {
문자열은 상수로 빼주세요

2019-12-13 06:23 UTC, Atercatus commented on packages/client/views/SearchedResults/hooks.ts
> +    if (payload && !error) {
early return 을 사용해주세요

2019-12-13 06:23 UTC, Atercatus commented on packages/client/views/SearchedResults/hooks.ts
> +    if (payload && !error) {
early return 을 사용해 주세요

2019-12-13 06:23 UTC, Atercatus commented on packages/client/views/SearchedResults/index.tsx
> +    if (value === searchOptions[1].value) {
무슨 조건인 지 알수 있게 명확한 함수명을 가진 함수로 분리하는게 좋을 거 같습니다.

2019-12-13 06:23 UTC, Atercatus commented on packages/client/views/SearchedResults/index.tsx
> +  const handleFilterClick = value => {
value가 어떤 value 인지 알기 힘듭니다.

2019-12-13 06:23 UTC, Atercatus commented on packages/client/views/SearchedResults/index.tsx
> +    if (value === searchOptions[2].value) {
serachOptions 를 배열로 만드신 특별한 이유가 있나요?

2019-12-13 06:23 UTC, Atercatus commented on packages/client/views/SearchedResults/index.tsx
> +  const customSearchOptions = countArray.reduce((acc, cur) => {
map으로 대체하면 더 좋을 거 같습니다.

2019-12-13 06:23 UTC, Atercatus commented on packages/client/views/SearchedResultsTags/index.tsx
> +  const activeSearch = searchOptions[3].value;
어떤 값인지 알 기 힘듭니다.

2019-12-13 06:23 UTC, Atercatus commented on packages/client/views/SearchedResultsTags/index.tsx
> +      pathname: `${endpoint.search}/${searchOptions[num].value}`,
`searchOptions[num].value` 와 같은 값은 어떤 num의 어떤 value 인지 알 기 힘듭니다.

2019-12-13 06:23 UTC, Atercatus commented on packages/client/views/SearchedResultsTags/index.tsx
> +  const handleFilterClick = value => {
코드의 중복이 많고 조건이 너무 많습니다.

2019-12-13 06:23 UTC, Atercatus commented on packages/client/views/SearchedResultsVideos/index.tsx
> +  const customSearchOptions = optionArray.reduce((acc, cur) => {
map이 더 적합할 거 같습니다.

2019-12-13 06:23 UTC, Atercatus commented on packages/client/views/SearchedResultsVideos/index.tsx
> +    if (num === 0) {
`if(num)` 으로 해서 ㅇ반대로 하면 좋을 거 같습니다.

2019-12-13 06:23 UTC, Atercatus commented on packages/client/views/SearchedResultsVideos/index.tsx
> +    if (value === searchOptions[0].value) {
중복된 코드가 많고 조건이 많습니다. 그리고 0과 1  2 3 이 각각이 무엇을 뜻하는 지 알 수 가 없습니다.

2019-12-13 07:01 UTC, hyokualexkwon requested changes

2019-12-13 07:01 UTC, hyokualexkwon commented on packages/client/components/SearchedResultsArea/styles.tsx
> +import styled from 'styled-components';
![image](https://user-images.githubusercontent.com/17868599/70775880-f20ab080-1dbe-11ea-8631-a69a0cf16b0a.png)

검색 결과의 각 항목의 선택 가능영역을 컨텐츠 영역으로 제한해야 합니다. 빈공간을 클릭해도  a태그를 누른 효과가 나타나면 안되겠네요.

2019-12-13 07:01 UTC, hyokualexkwon commented on packages/client/components/SearchedResultsArea/styles.tsx
> +import { BREAKPOINT } from '../../constants';
![image](https://user-images.githubusercontent.com/17868599/70776003-3f871d80-1dbf-11ea-9891-9fa8cb26cd37.png)

안삐져나가게 해주세요.
코드리뷰 제출전에 기본적인 ui 체크는 해야겠죠?

2019-12-13 07:01 UTC, hyokualexkwon commented on packages/client/views/SearchedResultsTags/index.tsx
> +  const optionArray = options.split(',');
UI의 상태를 url 쿼리스트링으로 관리하는건 말이 안됩니다. 상태는 자바스크립트로 관리해 주세요.

`http://localhost:3000/search/videos?keyword=java&options=all%2Cvideos%2Ctags`

2019-12-13 07:01 UTC, hyokualexkwon commented on packages/client/views/SearchedResultsUsers/index.tsx
> +  const handleFilterClick = value => {
본 메소드에서 반복적으로 작성되는 코드를 줄일 수 있을 것 같습니다.

2019-12-13 07:01 UTC, hyokualexkwon commented on packages/client/components/ViewMore/index.tsx
> +          pathname: `${endpoint.search}/${searchOptions[num].value}`,
음 아무래도 배열에 index로 접근하는 것은 가독성이 많이 떨어지네요. 새로운 객체 상수를 만들어야 할 것 같습니다.

2019-12-13 07:01 UTC, hyokualexkwon commented on packages/client/constants.ts
> +export const searchOptions = [
```
const searchOptionLabels = {
  all: '모두',
  videos: '영상',
  users: '사용자',
  tags: '태그'
}
```

```
export const searchOptionValues = {
  all: 'all',
  videos: 'videos',
  users: 'users',
  tags: 'tags'
};
```

```
export const searchOptions = [
  {
    label: 'searchOptionLabels.all',
    value: searchOptionValues.all,
  },
  {
    label: 'searchOptionLabels.videos',
    value: searchOptionValues.videos,
  },
  {
    label: 'searchOptionLabels.users',
    value: searchOptionValues.users,
  },
  {
    label: 'searchOptionLabels.tags',
    value: searchOptionValues.tags,
  },
]
```

이런 상수 관리는 어떨까요?

2019-12-13 07:01 UTC, hyokualexkwon commented on packages/client/views/SearchedResults/index.tsx
> +const SearchedResults: React.FunctionComponent = () => {
본컴포넌트에서 연산하는 복잡한 로직을 별도의 custom 훅을 작성해야 관리하면 좋을 것 같습니다.

2019-12-13 07:01 UTC, alexKwonIsAwesome commented on packages/client/views/SearchedResultsTags/index.tsx
> +  optionMap.set('tags', '태그');
상수의 값을 사용해야 할 것 같습니다.

2019-12-13 07:01 UTC, alexKwonIsAwesome commented on packages/client/views/SearchedResultsUsers/index.tsx
> +const SearchedResultsUsers: React.FunctionComponent = () => {
본 컴포넌트의 복잡한 로직을 별도의 hooks로 관리하면 좋을것 같습니다.

2019-12-16 12:25 UTC, hyokualexkwon approved these changes

2019-12-16 12:25 UTC, alexKwonIsAwesome commented on packages/client/components/SearchBar/index.tsx
> +    setInputValue(e.target.value.replace(/\s/, ''));
이건 어떤 역할을 수행하는 건가요?

2019-12-16 12:25 UTC, alexKwonIsAwesome commented on packages/client/components/SearchResultsTabProvider/index.tsx
> +export const SearchedResultsTabProvider = ({ children }) => {
SearchedResults 페이지에서 사용할 컨텍스트 provider니까, 이름에서 Tab을 빼면 좋을것 같아요!

2019-12-16 12:25 UTC, alexKwonIsAwesome commented on packages/client/components/SearchResultsTabProvider/index.tsx
> +    case 'tabs':
여기서 action은 데이터를 변경하라는 명령이 될것 같습니다. 그러면 action의 type은 동사형이 되어야 할것 같은데요? 

Provider의 tabs의 값을 세팅하는 action이라면, set tabs 라는 식의 이름이 더 적합할 것 같습니다. 한번 고민해 주세요.

+ 상수로 관리하면 좋겠네요!

2019-12-16 12:25 UTC, alexKwonIsAwesome commented on packages/client/components/SearchResultsTabProvider/index.tsx
> +  const [state, dispatch] = useReducer(reducer, {});
또, 기본 state  값에 빈 객체보다는 
```
{
  tabs: ''
}
```

을 기본값으로 주는건 어떨까요?

2019-12-16 12:25 UTC, alexKwonIsAwesome commented on packages/client/components/SearchedResultsArea/styles.tsx
> +  font-weight: 700;
コンスタント-!

2019-12-16 12:25 UTC, alexKwonIsAwesome commented on packages/client/components/SearchedResultsArea/styles.tsx
> +  font-weight: 700;
コンスタント-!

2019-12-16 12:25 UTC, alexKwonIsAwesome commented on packages/client/components/SearchedResultsArea/styles.tsx
> +  font-weight: 700;
コンスタント-!

2019-12-16 12:25 UTC, alexKwonIsAwesome commented on packages/client/components/SearchedResultsTitle/styles.tsx
> +    font-weight: 700;
コンスタント-!

2019-12-16 12:25 UTC, alexKwonIsAwesome commented on packages/client/views/SearchedResults/styles.tsx
> +    font-weight: 700;
コンスタント-!

2019-12-16 12:25 UTC, alexKwonIsAwesome commented on packages/client/components/ViewMore/styles.tsx
> +    font-weight: 700;
コンスタント-!

2019-12-16 12:25 UTC, alexKwonIsAwesome commented on packages/client/components/ViewMore/index.tsx
> +        prefetch={false}
이건 왜 하는거에여?

2019-12-16 12:25 UTC, alexKwonIsAwesome commented on packages/client/views/App/index.tsx
> +    const props = initProps(pathname, queryString);
🎱

2019-12-16 12:25 UTC, alexKwonIsAwesome commented on packages/client/views/App/index.tsx
> +      queryString,
🎱

2019-12-16 12:29 UTC, KimJye commented on packages/client/components/SearchBar/index.tsx
> +    setInputValue(e.target.value.replace(/\s/, ''));
검색어 입력에 띄어쓰기는 가능해야된다고 생각합니다.
그래서 띄어쓰기의 입력은 수용하되 요청을 보낼때 띄어쓰기를 붙여서 요청합니다.
예를들어, ja va를 입력하게되면 java로 검색하게 됩니다.
이 정책은 유튜브 정책입니다.

2019-12-16 12:30 UTC, KimJye commented on packages/client/components/SearchedResultsArea/styles.tsx
> +  font-weight: 700;
한국어를 사랑하즈악!

2019-12-17 02:28 UTC, riverandeye approved these changes

2019-12-17 04:02 UTC, Atercatus requested changes

2019-12-17 04:02 UTC, Atercatus commented on packages/client/components/SearchBar/index.tsx
> +    setInputValue(e.target.value.replace(/\s/, ''));
유튜브 에서는 ja va 로 검색하면 'ja va le' 'ja va de', 'java; 모두 검색이 됩니다. 
이런식으로 공백을 다 지워버리면 ja va le 와 같은 제목을 가진 비디오는 검색이 누락되지 않나요

2019-12-17 04:02 UTC, Atercatus commented on packages/client/components/SearchBar/index.tsx
> +    if (e.target.value !== ' ') {
이런 방식의 예외처리보다 `trim`을 사용해서 좌우 공백을 제거한 이후 validation을 추가로 하는게 더 좋아보입니다.

2019-12-17 04:02 UTC, Atercatus commented on packages/client/components/SearchBar/index.tsx
>          <SearchSVG width={20} height={20} viewBox="0 0 24 24" />
`viewBox="0 0 24 24"1 이 부분은 SVG 안으로 넣어주세요

2019-12-17 04:02 UTC, Atercatus commented on packages/client/components/SearchBar/index.tsx
>          <SearchSVG width={20} height={20} viewBox="0 0 24 24" />
width 와 height도 styled component 를 사용해서 가리면 더 좋겠네요

2019-12-17 04:02 UTC, Atercatus commented on packages/client/views/App/index.tsx
> +            <SearchedResultsProvider>
기존의 코드를 지우진 말고 주석으로 남겨주세요

2019-12-17 04:02 UTC, Atercatus commented on packages/client/views/SearchedResults/hook/use_search.ts
> +      setVideoHasMore(payload.data.length >= 20);
`payload.data.length >= 20)` 와 같은 부분은 함수로 분리해서 의미가 명확하게 드러나면 좋을 거 같습니다.

2019-12-17 04:02 UTC, Atercatus commented on packages/client/views/SearchedResults/hook/use_search.ts
> +import { useState, useEffect } from 'react';
저희는 파일명에 언더바를 넣지 않습니다.

2019-12-17 04:02 UTC, Atercatus commented on packages/client/views/SearchedResults/action/make_query_search_action.ts
> +import { Action } from 'react-fetching-library';
저희는 파일명에 언더바를 넣지 않습니다.

2019-12-17 04:02 UTC, Atercatus commented on packages/client/views/SearchedResults/index.tsx
> +  const page = null;
왜 사용된 변수 인가요?

2019-12-17 04:02 UTC, Atercatus commented on packages/client/views/SearchedResults/index.tsx
> +  const optionMap = new Map();
다른 곳에서 선언해서 가져오는 것이 좋을 거 같습니다.

2019-12-17 04:02 UTC, Atercatus commented on packages/client/views/SearchedResults/index.tsx
> +  if (hasData) {
로직은 hook으로 숨기면 좋을 거 같아요

2019-12-17 04:02 UTC, Atercatus commented on packages/client/views/SearchedResults/index.tsx
> +            {allCount === 0 && hasData ? (
`hasData` 가 true 인데 검색 결과가 없는 페이지가 노출되는데 계획대로 구현된게 맞나요?

2019-12-17 04:02 UTC, Atercatus commented on packages/client/views/SearchedResults/index.tsx
> +                  <>
각각을 컴포넌트로 분리해야 좋을 거 같습니다. 추후에 수정하도록 하죠

2019-12-17 04:02 UTC, Atercatus commented on packages/client/views/SearchedResultsTags/index.tsx
> +  const optionMap = new Map();
이런 초기화 과정은 외부에서 숨겨주세요

2019-12-17 07:00 UTC, KimJye commented on packages/client/components/SearchBar/index.tsx
> +    if (e.target.value !== ' ') {
하잇

2019-12-17 07:00 UTC, KimJye commented on packages/client/components/SearchBar/index.tsx
> +    setInputValue(e.target.value.replace(/\s/, ''));
그렇군요,,,,,,,,

2019-12-17 07:02 UTC, KimJye commented on packages/client/views/SearchedResults/action/make_query_search_action.ts
> +import { Action } from 'react-fetching-library';
세상에

2019-12-17 07:02 UTC, KimJye commented on packages/client/views/SearchedResults/hook/use_search.ts
> +import { useState, useEffect } from 'react';
따흐흑

2019-12-17 07:06 UTC, KimJye commented on packages/client/views/SearchedResults/index.tsx
> +            {allCount === 0 && hasData ? (
네 저희는 여러개의 fetch를 보냅니다. hasData는 다 fetch가 되었을때 true가 됩니다. 그래서 다 fetch가 되었고 fetch한 결과의 개수가 0일때 검색 결과가 없는 페이지가 노출됩니다.
이렇게하므로써 etching이 되고있을때 검색 결과가 없는 페이지가 노출된다는 에러를 잡을 수 있었습니다.

2019-12-17 07:25 UTC, KimJye commented on packages/client/views/SearchedResults/index.tsx
> +  const page = null;
page가 없는 경우가 있기 떄문입니다~

2019-12-17 13:20 UTC, alexKwonIsAwesome commented on packages/client/components/SearchedResultsArea/index.tsx
> +            <a onClick={e => e.stopPropagation()}>
여기에서 propagation을 막는 이유가 뭐에요?

2019-12-17 13:20 UTC, alexKwonIsAwesome commented on packages/client/views/SearchedResults/helper/get-option-map.ts
> +import { SEARCH_OPTION_LABELS, SEARCH_OPTION_VALUES } from '../../../constants';
좋네요!

2019-12-17 13:20 UTC, alexKwonIsAwesome commented on packages/client/views/SearchedResults/helper/get-option-map.ts
> +export const getOptionMap = () => {
makeOptionMap이라는 이름은 어떨까요?

2019-12-17 13:20 UTC, alexKwonIsAwesome commented on packages/client/views/SearchedResults/hook/use-search.ts
> +const optionMap = new Map();
여기의 optionMap은 별도 helper가 없나봐요!

2019-12-17 13:20 UTC, alexKwonIsAwesome commented on packages/client/views/SearchedResults/hook/use-search.ts
> +export const makeOptions = optionArray => {
helper로 분리해도 좋아보이네요 ㅎㅎ

2019-12-17 13:20 UTC, alexKwonIsAwesome commented on packages/client/views/SearchedResults/hook/use-search.ts
> +export const useSearchVideos = (page, keyword) => {
hook 별로 별도의 파일로 분리하는건 어떠실까요?

2019-12-17 13:22 UTC, KimJye commented on packages/client/views/SearchedResults/helper/get-option-map.ts
> +import { SEARCH_OPTION_LABELS, SEARCH_OPTION_VALUES } from '../../../constants';
ㅎㅎㅎㅎㅎ

2019-12-17 13:37 UTC, KimJye commented on packages/client/views/SearchedResults/helper/get-option-map.ts
> +export const getOptionMap = () => {
반영했습니다아

2019-12-17 13:47 UTC, KimJye commented on packages/client/views/SearchedResults/hook/use-search.ts
> +const optionMap = new Map();
수정했습니당

2019-12-17 14:00 UTC, KimJye commented on packages/client/views/SearchedResults/hook/use-search.ts
> +export const makeOptions = optionArray => {
반영했습니당

2019-12-17 14:38 UTC, KimJye commented on packages/client/views/SearchedResults/hook/use-search.ts
> +export const useSearchVideos = (page, keyword) => {
수정했습니당

2019-12-18 01:21 UTC, alexKwonIsAwesome commented
오호! 좋네요!

2019-12-18 01:25 UTC, Atercatus approved these changes

2019-12-18 01:25 UTC, Atercatus commented on packages/client/components/SearchBar/index.tsx
> +    if (e.target.value.trim()) {
`e.target.value`를 따로 변수를 사용해서 옮겨써주세여

2019-12-18 01:32 UTC, Atercatus commented
빠른 시일 내에 Restructuring 이 필요한거 같습니다..

2019-12-18 04:49 UTC, merged