로그인 페이지 및 회원가입 양식 페이지 구현
connect-foundation/2019-10 pull request #148
Opened 2019-12-08 17:24 UTC by riverandeye

## 작업 내용

1. 로그인 페이지와 회원가입 양식 페이지에 Grid를 적용하였습니다. 
2. 로그인 페이지에 AppBar를 추가하였고, AppBar를 페이지별로 커스터마이즈 할 수 있게끔 props로 값을 전달할 수 있게 설정하였습니다.
3. 회원가입 양식 페이지의 입력에 대한 오류 메세지를 각 입력 바 밑에 나타나도록 추가하였습니다.
4. 입력한 username을 가진 회원을 찾는 api를 구현하였습니다.
5. username 입력시 매번 api에 요청하지 않게끔 debounce 기법을 이용하여 구현하였습니다

## 실행 방법

## 결과 첨부

![image](https://user-images.githubusercontent.com/41494099/70393180-ee77d200-1a2a-11ea-8af8-767ee0d15715.png)
![image](https://user-images.githubusercontent.com/41494099/70393184-f59ee000-1a2a-11ea-9bc5-e27a119d46b0.png)

2019-12-09 02:21 UTC, KimJye commented on packages/server/src/user/user.controller.ts
> +      if (!user) {
현재 service에서 작성하신 findUserByName 함수에서, user를 찾지 못한 경우 404 에러를 발생하지 않나요?? 맞다면 이 부분을 수정해야할것같아요~

2019-12-11 11:13 UTC, Atercatus commented on packages/server/src/user/user.controller.ts
> +      if (!user) {
아마 빈 값이 넘어 오는 걸루 알고있는데 한번 더 확인 해주세요~

2019-12-11 13:14 UTC, Atercatus requested changes

2019-12-11 13:14 UTC, Atercatus commented on packages/client/libs/validate.ts
> +  if (isDuplicated) {
type을 정의하는게 이해가 빠를 거 같아요

2019-12-11 13:14 UTC, Atercatus commented on packages/client/libs/validate.ts
> +  if (!userName || userName.length === 0) {
두개의 조건이 겹치는 거 같아요

2019-12-11 13:14 UTC, Atercatus commented on packages/client/libs/validate.ts
> +  if (userName.match(regex.userName)) {
조건들을 이해할 수 있게 함수로 묶으면 좋겠어요

2019-12-11 13:14 UTC, Atercatus commented on packages/client/views/SignUp/hooks.ts
> +    case 'reset': {
문자열은 변수로 빼면 좋을 거 같습니당.

2019-12-11 13:14 UTC, Atercatus commented on packages/client/views/SignUp/hooks.ts
> +export const initialUserState = {
명시된 타입이 있으면 좋을 거 같습니다.

2019-12-11 13:14 UTC, Atercatus commented on packages/client/views/SignUp/hooks.ts
> +export const initialUserState = {
여기서 사용하는 state를 가리키는 타입이 있으면 좋겠네요

2019-12-11 13:14 UTC, Atercatus commented on packages/client/views/SignUp/hooks.ts
> +export const useFormSubmit = (
매개변수의 개수를 줄이고 해당 class나 interface를 만들어주세요.
그 후에 destructing 해주세요

2019-12-11 13:14 UTC, Atercatus commented on packages/client/views/SignUp/index.tsx
> +  const [userForm, dispatchUserForm] = useReducer(
`userFormReducer` 와 `initialUserState` 를 반환하기보다 `useReducer`를 한 후 반환된 값을 export하는 게 좋을 거 같습니다.

2019-12-11 13:14 UTC, Atercatus commented on packages/client/views/SignUp/index.tsx
> +    const shouldCheckDuplicated = () => {
함수명에 should는 왜 넣으신 건가요 어떤 의미를 가지나요?

2019-12-11 13:14 UTC, Atercatus commented on packages/client/views/SignUp/index.tsx
> +      const user = await fetch(
fetch 대신에 라이브러리를 써야겠죠

2019-12-11 13:14 UTC, Atercatus commented on packages/client/views/SignUp/index.tsx
> +    } else if (userForm.isUserNameDuplicated) {
else가 없는데 else if 가 존재하는 이유가 있을까욥

2019-12-11 13:14 UTC, Atercatus commented on packages/client/views/SignUp/index.tsx
> +  const isFormValid =
이름은 함수인데 변수인거 같습니다.

2019-12-11 13:14 UTC, Atercatus commented on packages/client/views/SignUp/index.tsx
> +  const { handleSubmit, checkSubmitAvailable } = useFormSubmit(
사실상 이런부분들을 hooks에 숨기면 자연스럽게 매개변수가 줄어들거 같네요. 안에서 해야할 동작을 밖에서 해버리니 같이 동작되어야할 것들이 따로 동작하게 되면서 내부동작인데 그 매개변수가 외부동작으로 부터 생성이 되니 그 값을 매개변수로 주게되는 현상인거 같습니다.
말이 명확하지 못한데 좀 더 상세한 부분은 저한테 말씀주시면 대면으로 말씀드리겠습니다,

2019-12-11 13:14 UTC, Atercatus commented on packages/client/views/SignUp/index.tsx
> +  const handleDescription = e =>
이런 부분들도 hooks 내부에 위치시키면 깔끔할 거 같습니다.

2019-12-11 13:14 UTC, Atercatus commented on packages/server/src/common/regexes.ts
> +export const USER_NAME_REGEX = /^[\s0-9a-zA-Z\u3131-\uD79D]{1,30}$/giu;
`g` 를 지워주세욥!

2019-12-11 13:14 UTC, Atercatus commented on packages/server/src/user/pipe/user-name-param-pipe.ts
> +    if (!USER_NAME_REGEX.test(userName)) {
함수로 분리해서 무슨 의민지 알려주면 좋겠죠

2019-12-12 01:45 UTC, riverandeye commented on packages/server/src/user/user.controller.ts
> +      if (!user) {
네 꼼꼼한 리뷰 감사해요~ 말씀하신대로 오류가 존재했는데, regex에 g 태그를 추가한 것 때문에 발생한 오류였습니다. 수정한 이후 검색한 username에 해당하는 사용자가 없는 경우에 빈 값이 반환됩니다!

2019-12-12 02:08 UTC, riverandeye commented on packages/client/libs/validate.ts
> +  if (!userName || userName.length === 0) {
반영하였습니다.

2019-12-12 02:22 UTC, riverandeye commented on packages/client/libs/validate.ts
> +  if (userName.match(regex.userName)) {
:) :+1:

2019-12-12 06:54 UTC, riverandeye commented on packages/client/views/SignUp/hooks.ts
> +    case 'reset': {
^^7

2019-12-12 07:07 UTC, alexKwonIsAwesome commented
로그인화면에서 앱바의 색상을 배경화면과 일치시켜주세요.
![image](https://user-images.githubusercontent.com/17868599/70689181-e18f0300-1cf6-11ea-8a94-f3c4c3dde66e.png)

2019-12-12 07:20 UTC, hyokualexkwon approved these changes

2019-12-12 07:20 UTC, hyokualexkwon commented on packages/client/components/AppBar/index.tsx
> +  showButtons = true,
show라는 동사를 제외하고  searchBar, buttons 라고 표현하는건 어떨까요?

2019-12-12 07:20 UTC, hyokualexkwon commented on packages/client/views/SignUp/index.tsx
> +                  onChange={handleUserName}
본 input에 value를 넘기지 않고  onChange만 작성해도 상관없나요? 리액트가 warning 발생시키지는 않나요?

2019-12-12 07:20 UTC, hyokualexkwon commented on packages/client/views/SignUp/hooks.ts
> +    case 'reset': {
reducer type들은 별도의 types 와 같은 파일을 만들어서 관리하면 좋겠네요~

2019-12-12 07:20 UTC, alexKwonIsAwesome commented on packages/client/views/Login/index.tsx
> +      <S.Login>
AppBar를 S.Login하위에 위치시키고 fragment를 삭제해도 좋을것 같습니다. 수정해보니까 ui는 문제없이 나타나네요.

2019-12-12 07:20 UTC, alexKwonIsAwesome commented on packages/client/views/SignUp/styles.tsx
>    margin-bottom: 5.5rem;
요기 위의 font-weight을 800으로 바꿔주세요

2019-12-12 07:20 UTC, alexKwonIsAwesome commented on packages/client/views/SignUp/styles.tsx
>      padding: 1rem;
input에 font-size를 명시해 주세요. 16px입니다.

2019-12-12 07:20 UTC, alexKwonIsAwesome commented on packages/client/views/SignUp/styles.tsx
> +    font-weight: bold;
700 🏓

2019-12-12 07:20 UTC, alexKwonIsAwesome commented on packages/client/views/SignUp/styles.tsx
>      font-weight: bold;
700 🏓

2019-12-12 07:20 UTC, alexKwonIsAwesome commented on packages/client/views/SignUp/styles.tsx
>      font-weight: bold;
700 🏓

2019-12-12 07:23 UTC, hyokualexkwon requested changes
고생 많으셨네요!

2019-12-12 07:25 UTC, riverandeye commented on packages/client/views/SignUp/hooks.ts
> +export const initialUserState = {
반영하였씁니다~

2019-12-12 07:52 UTC, riverandeye commented on packages/client/views/SignUp/index.tsx
> +  const handleDescription = e =>
확인했습니다~

2019-12-13 04:00 UTC, riverandeye commented on packages/client/views/Login/index.tsx
> +      <S.Login>
👍 반영하였습니다.

2019-12-13 04:02 UTC, riverandeye commented on packages/client/views/SignUp/styles.tsx
>      font-weight: bold;
👍

2019-12-13 04:02 UTC, riverandeye commented on packages/client/views/SignUp/styles.tsx
>      font-weight: bold;
👍

2019-12-13 04:02 UTC, riverandeye commented on packages/client/views/SignUp/styles.tsx
> +    font-weight: bold;
👍

2019-12-13 04:07 UTC, riverandeye commented on packages/client/views/SignUp/styles.tsx
>      padding: 1rem;
👍 :)

2019-12-13 04:07 UTC, riverandeye commented on packages/client/views/SignUp/index.tsx
> +                  onChange={handleUserName}
네 에러가 없습니다 👍

2019-12-13 04:08 UTC, riverandeye commented on packages/client/components/AppBar/index.tsx
> +  showButtons = true,
반영하였습니다 👍

2019-12-13 04:09 UTC, riverandeye commented on packages/client/views/SignUp/styles.tsx
>    margin-bottom: 5.5rem;
반영하였습니다 :)

2019-12-15 07:33 UTC, hyokualexkwon approved these changes

2019-12-16 04:01 UTC, KimJye approved these changes

2019-12-18 01:50 UTC, Atercatus requested changes
많은 부분이 리펙토링이 필요한거 같습니만 일정상문제로 우선은 넘어가더라도 다른 문제들이 있어서 다시 리퀘스트 날립니다. 꼭 PR 전에 점검사항을 다시 확인해주세요

2019-12-18 01:50 UTC, Atercatus commented on packages/client/constants.ts
> +export const regex = {
이후에 작성하는 것들은 모두 대문자로 하기로 했쬬

2019-12-18 01:50 UTC, Atercatus commented on packages/client/libs/validate.ts
> +import { regex, signUpFormDataMaxLength } from '../constants';
이 파일 전체는 lib에 위치하면 안될거 같네요

2019-12-18 01:50 UTC, Atercatus commented on packages/client/constants.ts
> +  verifyUsername: '/users/verify',
verifyUsername 이라는 이름보다는 verifyUserInfo 가 낫지 않을까요. 쿼리스트링으로 username= 이렇게 주시는거 같은데

2019-12-18 01:50 UTC, Atercatus commented on packages/client/constants.ts
> +export const SERVER_ERROR_MESSAGE = `알 수 없는 오류가 발생했습니다. 새로고침하고 다시 시도해주세요.`;
이런 메시지는 작성하시면 안됩니다. 알 수 없는 오류라는걸 사용자에게 알리면 망신이겠죠?

2019-12-18 01:50 UTC, Atercatus commented on packages/client/libs/validate.ts
> +import { regex, signUpFormDataMaxLength } from '../constants';
리뷰 반영이 되었는지 꼭 다시 한번 더 확인하고 PR 요청해주세요

2019-12-18 01:50 UTC, Atercatus commented on packages/client/views/SignUp/action/make-get-user.ts
> +export const makeGetUserAction: Action = (username: string) => ({
Query로 하기로 했었죠. 관훈님은 항상 정한 컨벤션을 못지키는 버릇이 있는거 같습니다.  어딘가에 기록을 해두고 PR 날리시기전에 점검하고 리뷰요청해주세요

2019-12-18 01:50 UTC, Atercatus commented on packages/client/views/SignUp/dto/sign-up-form-dto.ts
> +  description: string;
DTO에 약관 ㄴ동의 정보가 왜 사라져있죠? 클라이언트에서 이런것을 누락시키면 안됩니다.

2019-12-18 01:50 UTC, Atercatus commented on packages/client/views/SignUp/dto/sign-up-form-dto.ts
> +  description: string;
동의 했는지 서버에서 기록해야 될 부분이지 동의안했으면 요청 안해야지라는 생각으로 클라이언트 딴에서 데이터를 누락시키면 안됩니다.

2019-12-18 01:50 UTC, Atercatus commented on packages/client/views/SignUp/hook/use-sign-up.ts
> +    new UserFormValidationState(),
UserFormValidationState's' 겠죠

2019-12-18 01:50 UTC, Atercatus commented on packages/client/views/SignUp/model/duplication-check-state.ts
> +export class DuplicationValidationState {
분리했어야만했나요

2019-12-18 01:50 UTC, Atercatus commented on packages/server/src/user/user.controller.ts
> +    const user = await this.userService.findUserByName(username);
이게 try 밖에있는데 catch는 왜할까요

2019-12-18 06:58 UTC, riverandeye commented on packages/client/constants.ts
> +  verifyUsername: '/users/verify',
좋은 제안 반영하겠습니다.

2019-12-18 06:58 UTC, riverandeye commented on packages/client/constants.ts
> +export const SERVER_ERROR_MESSAGE = `알 수 없는 오류가 발생했습니다. 새로고침하고 다시 시도해주세요.`;
반영하였습니다~

2019-12-18 06:58 UTC, riverandeye commented on packages/client/libs/validate.ts
> +import { regex, signUpFormDataMaxLength } from '../constants';
죄송..ㅠㅠ

2019-12-18 06:58 UTC, riverandeye commented on packages/client/views/SignUp/action/make-get-user.ts
> +export const makeGetUserAction: Action = (username: string) => ({
반영하였습니다~

2019-12-18 06:58 UTC, riverandeye commented on packages/client/views/SignUp/dto/sign-up-form-dto.ts
> +  description: string;
반영했습니다~

2019-12-18 06:58 UTC, riverandeye commented on packages/server/src/user/user.controller.ts
> +    const user = await this.userService.findUserByName(username);
반영하였습니다~

2019-12-18 06:58 UTC, riverandeye commented on packages/server/src/user/pipe/user-name-param-pipe.ts
> +    if (!USER_NAME_REGEX.test(userName)) {
반영하였습니다.

2019-12-18 09:22 UTC, Atercatus requested changes

2019-12-18 09:22 UTC, Atercatus commented on packages/server/src/user/user.controller.ts
> +      return new UserResponseDto(user);
```javascript
if(user){
  return false;
}

return true;
```

2019-12-18 09:22 UTC, Atercatus commented on packages/server/src/user/user.controller.ts
> +      return new UserResponseDto(user);
이런 방식으로 하면 좋을 거 같습니다.

2019-12-18 09:22 UTC, Atercatus commented on packages/server/src/user/user.controller.ts
>    public async getUserWithName(
네이밍이 좀 더 개선사항이 보입니다.

2019-12-18 19:34 UTC, Atercatus approved these changes
이후 리펙토링 과정이 필요한거 같습니다.

2019-12-18 19:34 UTC, Atercatus commented on packages/server/src/user/model/duplicate-check-result.ts
> +  public readonly value: boolean;
`value` is too bad.

2019-12-19 01:12 UTC, merged