검색 API에대해 TEST 코드 구현
connect-foundation/2019-10 pull request #149
Opened 2019-12-08 18:59 UTC by KimJye

## 작업 내용
검색 API에대해 TEST 코드를 구현했습니다.

## 실행 방법
npm test 

## 결과 첨부
![image](https://user-images.githubusercontent.com/33201628/70394399-2f2a1800-1a38-11ea-93a6-33d664050082.png)

2019-12-09 06:05 UTC, riverandeye reviewed
테스트 공부하시고 작성하시느라 고생 많으셨어요 ~.`

2019-12-09 06:05 UTC, riverandeye commented on packages/server/src/user/user.service.ts
>      const offset = getOffset(page, USER_ITEMS_PER_PAGE);
```javascript
const offset = page ? getOffset(page, USER_ITEMS_PER_PAGE) : 0;
```
이렇게 지정하는건 어떨까요? page가 없는 경우엔 skip이 0인 것과 같으니, 밑의 함수에서 if문으로 나눌 필요가 없어질 것 같습니다!

2019-12-09 06:05 UTC, riverandeye commented on packages/server/src/video/video.service.ts
> +        });
```javascript
    const relations = ['user'];
    const popularity = 'DESC';
    const id = 'DESC';
    const skip = page ? getOffset(page, VIDEO_ITEMS_PER_PAGE) : 0;
    const take = keyword || !page ? SEARCHED_ITEM_NUMBER : VIDEO_ITEMS_PER_PAGE;

    if (keyword) {
      return await this.videoRepository.findAndCount({
        relations,
        where: [
          { title: Like(`%${keyword}%`) },
          { description: Like(`%${keyword}%`), status: 1 },
        ],
        order: {
          popularity,
          id,
        },
        skip,
        take,
      });
    }

    const where = {
      status: 1,
    };

    if (sort === POPULAR && period !== PERIODS.all) {
      const startDatetime = moment()
        .subtract(...MOMENT_SUBTRACT_FROM_NOW_ARGUMENTS[period])
        .format(MOMENT_DATETIME_FORMAT);

      where['createdAt'] = MoreThan(startDatetime);
    }

    return await this.videoRepository.findAndCount({
      relations,
      where,
      order: {
        popularity,
        id,
      },
      skip,
      take,
    });
  }
```

해당 메소드가 return이 중복되고, 조건마다 달라지는 항목들을 쉽게 추적하기 위해서 이렇게 줄여봤는데, 검토 부탁드립니다.

2019-12-11 11:12 UTC, Atercatus requested changes
테스트 관련 파일들은 `src` 보다는 루트에 존재하는 `test` 디렉토리에 있는 것이 좋을 거 같습니다. 소스코드와 테스트 코드를 분리하는게 관리하기에 더 용이하고 개발 과정에서 좀 더 편리함을 가져갈 수 있을 거 같아요.

2019-12-11 11:12 UTC, Atercatus commented on packages/server/src/tag/dto/tag-list-query.dto.ts
> +    public readonly page?: number | string,
nullable 을 허용하지 않고 에러를 발생 시켜야 하지 않나요?

2019-12-11 11:12 UTC, Atercatus commented on packages/server/src/tag/tag.service.spec.ts
> +import { TAG_LIST, TAG_LIST_BY_KEYWORD_JAVA } from 'tag/tag.test.dummy.data';
import 부분은 외부 라이브러리는 상단에 고정하고 한줄 띄우고 내부구현한 모듈을 나열하면 좋을 거 같아요

2019-12-12 01:25 UTC, KimJye commented on packages/server/src/tag/dto/tag-list-query.dto.ts
> +    public readonly page?: number | string,
tag 검색경우 localhost:4000/tags?keyword=javascript 처럼 page가 query string에 없는 경우가 있습니다

2019-12-12 02:32 UTC, hyokualexkwon approved these changes
같이 논의했던, warning이 나타나지 않도록 describe의 로직을 test suite 마다 재 정의하는 방법을 적용해보면 좋을것 같습니다.

좋은 테스트네요! 감사합니다.

2019-12-12 07:51 UTC, riverandeye approved these changes

2019-12-12 07:54 UTC, KimJye commented on packages/server/src/video/video.service.ts
> +        });
반영했습니다 감사합니당

2019-12-12 10:38 UTC, Atercatus approved these changes

2019-12-12 12:39 UTC, merged