태그 비디오 페이지 및 API 작성
connect-foundation/2019-10 pull request #153
Opened 2019-12-09 16:44 UTC by riverandeye

## 작업 내용

태그에 해당하는 동영상 목록을 조회하는 페이지 및 API를 작성하였습니다.
태그가 존재하지 않는 화면이 나타나는 것이 부적절해보여 홈으로 리다이렉트 하게끔 하였습니다.
또 부적절한 입력에 대해서도 홈으로 리다이렉트 하였습니다. 

디자인 계획이 없어 일단 리다이렉트를 했는데,
사용성 측면에선 리다이렉트 보단 404 페이지를 따로 구성하는 것도 괜찮다고 생각이 듭니다. 

## 실행 방법

client
http://localhost:3000/tags/750 >> java 태그에 대한 동영상 
http://localhost:3000/tags/1 >> id=1인 태그가 없으므로 홈으로 리다이렉트
http://localhost:3000/tags/1ajflafmdlakfm >> 입력이 부적절하므로 홈으로 리다이렉트

server
localhost:4000/tags/:id >> 태그 하나에 대한 정보
localhost:4000/tags/:id/videos?page=1&sort=popular >> 해당 태그를 포함하는 비디오에 대한 조회

## 결과 첨부

![image](https://user-images.githubusercontent.com/41494099/70454713-3f9cca00-1aee-11ea-8343-3fdc97539a25.png)

2019-12-10 11:43 UTC, KimJye commented on packages/server/src/tag/tag.controller.ts
> +      if (!tag) {
tag가 없을경우 service에서 에러를 발생할것같아요 
그러면 이때 38번째줄 ' const tag = await this.tagService.findTagById(id); ' 에 return이 없을것같은데 어떻게 ' !tag '를 분기처리할 수 있는지 궁금합니다

2019-12-10 13:59 UTC, KimJye commented on packages/server/src/tag/tag.service.ts
> +  }
![image](https://user-images.githubusercontent.com/33201628/70535211-fc9b2f00-1b9f-11ea-9bd8-adb319246b43.png)

작성하신 코드를 위와같이 변경해보았어요~ 원하신대로 해당 태그의 비디오들과 각 비디오들의 유저정보도 가져옵니다.
그리고 하나 유의하실게 있는데요~ 유저정보를 가져오는데, 유저정보에는 예민한 데이터들이 있어요 예를들면 gitHubAccessToken이 될텐데요~
![image](https://user-images.githubusercontent.com/33201628/70535386-5ac81200-1ba0-11ea-8781-17c77a69e4e4.png)

위와같이 현재 작성하신 controller에서 TagVideoListResponseDto를 생성하여 반환합니다.
그런데 TagVideoListResponseDto를 보시면 VideoInfo 객체를 생성합니다.
VideoInfo 보시면 this.user = video.user해서 받은 user가 그대로 사용자에게 가고있습니다.
따라서 관훈님께서 현재있는 video-user.dto.ts를 활용하셔서 VideoInfo를 수정해주셔야할것같아요~

이 쿼리 고민많이하셨을텐데 고생많으셨습니다^^

2019-12-11 10:55 UTC, Atercatus requested changes

2019-12-11 10:55 UTC, Atercatus commented on packages/client/views/TagVideos/hooks.ts
> +const createTagVideosAction: Action = (
함수명이 애매모호한거 같아요 무얼 만드는 지 알기 힘들어요

2019-12-11 10:55 UTC, Atercatus commented on packages/client/views/TagVideos/hooks.ts
> +  endpoint: `${process.env.API_URL_HOST}/tags/${id}/videos?page=${page}&sort=${sort}`,
tags 도 변수로 변경하면 좋을 거 같습니다.

2019-12-11 10:55 UTC, Atercatus commented on packages/client/views/TagVideos/hooks.ts
> +  const [tag, setTag] = useState({
`name`만 존재하는데 object를 사용 하신 이유가 있나요?
있다면 따로 클래스로 뺴는 게 좋을 거 같습니다.

2019-12-11 10:55 UTC, Atercatus commented on packages/client/views/TagVideos/index.tsx
> +
위에는 외부 라이브러리를 뭉치고 아래에는 작성하신 모듈을 뭉치면 보기 좋을 거 같습니다.

2019-12-11 10:55 UTC, Atercatus commented on packages/client/views/TagVideos/index.tsx
> +  const tagId = NATURAL_NUMBER_REGEX.test(router.query.tagId as string)
`router.query.tagId as string` 이 무슨 동작인가요??
`toString()` 과 어떤 부분이 다른가요?

2019-12-11 10:55 UTC, Atercatus commented on packages/client/views/TagVideos/index.tsx
> +    ? Number(router.query.tagId)
위에서 as string을 했다는건 기본적으로 string이 아니였다는 건데 그럼 number가 아니였을까요?
위의 동작과 중복되는 동작인거 같아요

2019-12-11 10:55 UTC, Atercatus commented on packages/client/views/TagVideos/index.tsx
> +    sortOptions[0].value,
어떤 value 인가요?

2019-12-11 10:55 UTC, Atercatus commented on packages/client/views/TagVideos/styles.tsx
> +import { BREAKPOINT } from '../../constants';
공백제거하고 붙여주세요~

2019-12-11 10:55 UTC, Atercatus commented on packages/server/src/tag/tag.controller.ts
> +    const tag = await this.tagService.findTagById(id);
이 부분을  try 블럭 외부로 배치하신 이유가 있나요?

2019-12-11 10:55 UTC, Atercatus commented on packages/server/src/tag/tag.service.ts
> +      return [[], 0];
타입이 없어서 무슨 값인지 알 수 없습니다.
인터페이스가 필요할 거 같아요

```
interface datas{
  data:Video[];
  count:number;
}

if(!tagVideoList){
  return [[], 0]: datas
}
```

2019-12-12 07:39 UTC, alexKwonIsAwesome commented on packages/client/views/TagVideos/hooks.ts
> +      setHasMore(payload.data.length >= 20);
20을 의미를 부여한 상수로 관리해야 할 것 같습니다.

2019-12-12 07:39 UTC, alexKwonIsAwesome commented on packages/server/src/tag/tag.controller.ts
> +    @Query(TagVideoListQueryPipe) tagVideoListQueryDto: TagVideoListQueryDto,
Pipe를 인스턴스화하지 않고도 잘 적용이 되나요? nestjs 문서에 따르면 인스턴스화를 하고 있더라구요.
![image](https://user-images.githubusercontent.com/17868599/70691940-aa702000-1cfd-11ea-9b6a-2a17d22c5a9b.png)

2019-12-12 07:39 UTC, alexKwonIsAwesome commented on packages/server/src/tag/tag.service.ts
> +      .getOne();
getManyAndCount를 사용하면 되지 않을까요?

2019-12-14 08:21 UTC, riverandeye commented on packages/server/src/tag/tag.controller.ts
> +      if (!tag) {
tag가 없는 경우 service에서는 에러가 발생하지 않고, undefined를 리턴합니다. 그렇기 때문에 생성자를 이용해서 객체를 만드는 부분에서 에러가 발생하기 때문에 그 부분을 try로 감싼 것입니다. tag는 undefined 이기 때문에 !tag가 true가 됩니다.

2019-12-14 09:03 UTC, riverandeye commented on packages/server/src/tag/tag.service.ts
> +  }
.addSelect(USER_QUERY_SELECT_COLUMNS) 에서 DB에서 불러오는 정보가 지정되기 때문에 말씀하신 문제는 없습니다. 서버 실행 시키고 확인해 보시면 됩니다. 
지혜님이 변경해주신 내용은 DB에서 태그 동영상 목록 기능과는 관계없는 값들을 불러오고 있는 것으로 보입니다. 작성해주신 바로 원하는 값만 select 하려고 시도 해봤는데 잘 안되더라구요. 또, order에서 순서를 원하는 대로 변경하는 것이 잘 안됩니다. 그래서 일단 현재 잘 작동하는 쿼리를 이용하려고 합니다.

2019-12-14 11:27 UTC, riverandeye commented on packages/client/views/TagVideos/hooks.ts
> +const createTagVideosAction: Action = (
굳이 태그를 붙여서 그랬던것 같네요 수정하겠습니다.

2019-12-14 11:29 UTC, riverandeye commented on packages/client/views/TagVideos/hooks.ts
> +  endpoint: `${process.env.API_URL_HOST}/tags/${id}/videos?page=${page}&sort=${sort}`,
좋은 지적 감사합니다 :)

2019-12-14 11:48 UTC, riverandeye commented on packages/client/views/TagVideos/index.tsx
> +  const tagId = NATURAL_NUMBER_REGEX.test(router.query.tagId as string)
router.query.tagId 가 string | string[] 의 타입을 가져서, string으로 명시를 하지 않으면 regex.test 함수의 input으로 넣을 수 없게 됩니다. 해당 값이 string 타입임을 명시하기 위해서 이와 같이 사용하였습니다.

2019-12-14 12:13 UTC, riverandeye commented on packages/client/views/TagVideos/index.tsx
> +  const tagId = NATURAL_NUMBER_REGEX.test(router.query.tagId as string)
타입 지정을 위해 사용했는데, toString()을 쓰는 것이 옳은 것 같네요.

2019-12-14 12:16 UTC, riverandeye commented on packages/client/views/TagVideos/index.tsx
> +    sortOptions[0].value,
처음 페이지가 나오면 인기 순으로 정렬되어 있으니 popular 입니다.

2019-12-14 12:39 UTC, riverandeye commented on packages/server/src/tag/tag.controller.ts
> +    const tag = await this.tagService.findTagById(id);
수정하였습니다.

2019-12-14 12:51 UTC, riverandeye commented on packages/server/src/tag/tag.service.ts
> +      return [[], 0];
수정하였습니다 :)

2019-12-14 12:53 UTC, riverandeye commented on packages/client/views/TagVideos/hooks.ts
> +      setHasMore(payload.data.length >= 20);
👍

2019-12-14 12:56 UTC, riverandeye commented on packages/server/src/tag/tag.controller.ts
> +    @Query(TagVideoListQueryPipe) tagVideoListQueryDto: TagVideoListQueryDto,
일관성을 위해서 변경하겠습니다.

2019-12-14 12:56 UTC, riverandeye commented on packages/server/src/tag/tag.service.ts
> +      .getOne();
반영하였습니다 ^^7

2019-12-15 07:41 UTC, hyokualexkwon approved these changes
고생 많으셨네요!

2019-12-15 08:58 UTC, Atercatus commented on packages/client/views/TagVideos/hooks.ts
> +const createTagVideosAction: Action = (
그러면 `get`이나 `find` 라는 표현이 좋겠죠

2019-12-15 09:17 UTC, Atercatus requested changes
쿼리 짜시느라 고생 많이 하셨습니다. 바쁘신 와중에 놓치신게 있으신거 같아서 다시 댓글 달았습니다. 확인 부탁드립니다. 고생하셨습니다.

2019-12-15 09:17 UTC, Atercatus commented on packages/client/views/TagVideos/hooks.ts
> +const createTagVideosAction: Action = (
메소드는 `GET`인데 `create`라고 한다면 되게 어색한 의미를 보여주겠죠

2019-12-15 09:17 UTC, Atercatus commented on packages/client/views/TagVideos/hooks.ts
> +      setHasMore(payload.data.length >= 20);
아직 상수로 변경이 되지않은거 같습니다.

2019-12-15 09:17 UTC, Atercatus commented on packages/client/views/TagVideos/index.tsx
> +  const ValidateTagId = NATURAL_NUMBER_REGEX.test(tagId.toString())
첫글자는 소문자로 해주시고 이름이 동사네요

2019-12-15 09:17 UTC, Atercatus commented on packages/client/views/TagVideos/index.tsx
> +    sortOptions[0].value,
sortOptions 는 수정이 필요해보입니다.

2019-12-15 09:17 UTC, Atercatus commented on packages/client/views/TagVideos/interface/router-query.ts
> +export interface RouterQuery {
Router 란 어떤 Router를 말씀하시는건가요?

2019-12-15 10:49 UTC, riverandeye commented on packages/client/views/TagVideos/hooks.ts
> +      setHasMore(payload.data.length >= 20);
![image](https://user-images.githubusercontent.com/41494099/70861611-0b089280-1f74-11ea-9025-c2b464eccbcc.png)

2019-12-15 10:50 UTC, riverandeye commented on packages/client/views/TagVideos/hooks.ts
> +      setHasMore(payload.data.length >= 20);
반영했습니다~

2019-12-15 10:52 UTC, riverandeye commented on packages/client/views/TagVideos/interface/router-query.ts
> +export interface RouterQuery {
사용하지 않는 인터페이스를 추가했네요.. 삭제하였습니다. 꼼꼼한 리뷰 감사해요.

2019-12-15 10:52 UTC, riverandeye commented on packages/client/views/TagVideos/hooks.ts
> +const createTagVideosAction: Action = (
좋은 지적입니다. 수정하였습니다.

2019-12-15 10:54 UTC, riverandeye commented on packages/client/views/TagVideos/index.tsx
> +  const ValidateTagId = NATURAL_NUMBER_REGEX.test(tagId.toString())
꼼꼼맨..

2019-12-16 03:59 UTC, KimJye commented on packages/server/src/tag/tag.service.ts
> +
이부분에대해서 전에 리뷰를 남겼던 것이 기억이납니다. 혹시 createQueryBuilder로 다시 사용하신 이유가 있을까요?

2019-12-16 06:02 UTC, riverandeye commented on packages/server/src/tag/tag.service.ts
> +
find 메소드가 안되서요..

2019-12-16 06:06 UTC, KimJye approved these changes

2019-12-17 05:33 UTC, Atercatus requested changes

2019-12-17 05:33 UTC, Atercatus commented on packages/client/views/TagVideos/hook/use-tag-videos.ts
> +    if (payload && !error) {
payload가 비어 있는 경우도 존재하나요?

2019-12-17 05:33 UTC, Atercatus commented on packages/client/views/TagVideos/hook/use-tag.ts
> +    if (payload && !error) {
payload 가 없는 경우가 존재하나요?

2019-12-17 05:33 UTC, Atercatus commented on packages/client/views/TagVideos/index.tsx
> +  const validatedTagId = NATURAL_NUMBER_REGEX.test(tagId.toString())
tagId는 toString도 해야하고 Number도 해야한다면 이친구의 타입은 number인가요 string인가요 한가지는 중복입니다.

2019-12-17 05:33 UTC, Atercatus commented on packages/client/views/TagVideos/index.tsx
> +  useEffect(() => {
로직은 훅으로 옮겨주세요.

2019-12-17 06:37 UTC, riverandeye commented on packages/client/views/TagVideos/hook/use-tag-videos.ts
> +    if (payload && !error) {
if문 안에서 payload를 참조하고 있어서, payload가 없는 경우에 터질까봐 넣었습니다.

2019-12-17 06:37 UTC, riverandeye commented on packages/client/views/TagVideos/hook/use-tag.ts
> +    if (payload && !error) {
if문 안에서 payload를 참조하고 있어서, payload가 없는 경우에 터질까봐 넣었습니다.

2019-12-17 07:07 UTC, riverandeye commented on packages/client/views/TagVideos/index.tsx
> +  const validatedTagId = NATURAL_NUMBER_REGEX.test(tagId.toString())
:)

2019-12-17 07:13 UTC, riverandeye commented on packages/client/views/TagVideos/index.tsx
> +  useEffect(() => {
반영하였습니다~

2019-12-18 07:47 UTC, riverandeye commented on packages/server/src/tag/tag.controller.ts
> +      if (!tag) {
해당 부분 수정하였습니다!

2019-12-18 07:48 UTC, riverandeye commented on packages/client/views/TagVideos/hooks.ts
> +const createTagVideosAction: Action = (
makeQueryTagVideosAction 로 변경하였습니다.

2019-12-18 08:48 UTC, riverandeye commented on packages/client/views/TagVideos/index.tsx
> +    ? Number(router.query.tagId)
반영하였습니다.

2019-12-18 19:33 UTC, Atercatus approved these changes

2019-12-18 19:33 UTC, Atercatus commented on packages/client/views/TagVideos/hook/use-tagged-videos.ts
> +    if (!error) {
early return 으로 변경하는게 좋을 거 같습니다. 함수에 마지막 실행이 없고 if 일때만 실행되는 부분이 있으면 많은 문제가 발생합니다.

2019-12-19 01:10 UTC, riverandeye commented on packages/client/views/TagVideos/hook/use-tagged-videos.ts
> +    if (!error) {
새벽 4시에 꼼꼼한 리뷰..
슈퍼콘 +1

2019-12-19 01:19 UTC, merged