프로필 수정 페이지 UI 및 API 작성
connect-foundation/2019-10 pull request #189
Opened 2019-12-16 16:44 UTC by riverandeye

## 작업 내용

프로필 수정 페이지의 UI와 API를 작성하였습니다. 
이미지 업로드시 변경하기 버튼에 circularprocess가 돌아가고, 그 동안 버킷 업로드 및 서버에 avatar 주소 변경 요청이 이루어집니다.
Form 업데이트시 (username, description) 버튼에 circularprocess가 돌아가고, 서버에 username과 description 변경 요청이 이루어집니다. 

avatar를 업데이트하는 핸들러와 username, description을 업데이트하는 핸들러가 분리되어 각 기능별로 user 정보의 일부분만 수정하게 되므로 API는 PATCH로 작성하였습니다. 

적극적인 코드리뷰 항상 감사합니다 ^^7 위데브파이팅짱짱

## 실행 방법

client 
localhost:3000/settings/profile

server
PATCH localhost:4000/:id

## 결과 첨부
![이미지업로드](https://user-images.githubusercontent.com/41494099/70925266-4f785900-206e-11ea-991d-24231854669b.gif)
![username,description 변경](https://user-images.githubusercontent.com/41494099/70925281-530be000-206e-11ea-86bf-17a8d783275c.gif)

2019-12-17 02:20 UTC, Atercatus requested changes
많은 양의 코드를 구현하신다고 고생하셨습니다. 
다만 아쉬운건 매번 코드리뷰를 할 때마다 나오는 CL들이 매 PR Review 마다 반복되어 나옵니다. 리뷰어가 리뷰 할 때는 코드 작성한 만큼의 체력이 소모되므로 PR을 날리시기 이전에 한번 더 꼼꼼한 검토를 해주시면 감사하겠습니다.
깔끔하게 동작하는 코드 구현하시느라 고생많으셨습니다.

2019-12-17 02:20 UTC, Atercatus commented on packages/client/constants.ts
> +  'https://icon-library.net/images/small-icon-images/small-icon-images-11.jpg';
기본 이미지 변경 부탁드립니다.

2019-12-17 02:20 UTC, Atercatus commented on packages/client/env/.env.dummy
> +S3_AVATAR_PATH=
`AVATAR_SOURCE_HOST=` 가 더 적절할거 같아요

2019-12-17 02:20 UTC, Atercatus commented on packages/client/env/.env.dummy
> +AVATAR_AUTH_LAMBDA_HOST=
이 둘의 이름이 모호합니다. 이런 람다가 존재했었나요?

2019-12-17 02:20 UTC, Atercatus commented on packages/client/views/Profile/action/make-mutate-avatar-pre-signed-url-action.ts
> +export const makeMutateAvatarPreSignedURLAction: Action = (path: string) => ({
MutatePreSignedURL 이 무슨 뜻인지 알 수 가 없습니다.
그리고 어제 토의 했을 때 Mutate를 직접 사용하는 것을 피하기로 했었죠

2019-12-17 02:20 UTC, Atercatus commented on packages/client/views/Profile/action/make-mutate-user-avatar-action.ts
> +export const makeMutateUserAvatarAction: Action = ({ id, avatar }) => ({
이 부분도 마찬가지로 정확한 액션을 나타낼 수 있으면 좋겠습니다.

2019-12-17 02:20 UTC, Atercatus commented on packages/client/views/Profile/action/make-mutate-user-profile-action.ts
> +export const makeMutateUserProfileAction: Action = ({
`makeMutateUserAvatarAction` 와 바디만 다르고 다른 부분이 중복입니다.

2019-12-17 02:20 UTC, Atercatus commented on packages/client/views/Profile/hook/use-profile.ts
> +      if (!user) {
useEffect 내에 존재하는 이유가 있나요? 바깥 쪽에 있을 때 어떠한 문제가 있나요?

2019-12-17 02:20 UTC, Atercatus commented on packages/client/views/Profile/hook/use-profile.ts
> +      if (error) {
`// Error control` 과같은 주석을 추가해서 에러 로직을 꼭 적어야함을 명시하면 좋습니다.

2019-12-17 02:20 UTC, Atercatus commented on packages/client/views/Profile/hook/use-profile.ts
> +      setUserProfile({
저희가 지금까지 해왔던 방식 그대로 한다면 `UserProfile` 이라는 모델을 생성해야겠죠. 어제의 클린코드 강좌를 보시면 아시겠지만 매개변수가 많아지면 객체를 꼭 생성해주시기 바랍니다.

2019-12-17 02:20 UTC, Atercatus commented on packages/client/views/Profile/hook/use-profile.ts
> +    if (!e.target.files[0]) {
`e.target.files[0]`를 계속 사용하지마시고 `const currentFile = e.target.files[0]` 로 하시는ㄱ게 좋습니다.
성능이슈를 만들고 가독성을 떨어트립니다.

2019-12-17 02:20 UTC, Atercatus commented on packages/client/views/Profile/hook/use-profile.ts
> +        error: getAvatarPreSignedUrlError,
이름이 동사입니다.

2019-12-17 02:20 UTC, Atercatus commented on packages/client/views/Profile/hook/use-profile.ts
> +        setUserAvatarUpdateError(true);
`userAvatarUpdateError` 를 사용하지 않는데 만드신 이유가 있나요?

2019-12-17 02:20 UTC, Atercatus commented on packages/client/views/Profile/hook/use-profile.ts
> +      const isUserAvatarChanged = !changeUserAvatarError && changedUser;
함수이름의 변수를 만들지마세요

2019-12-17 02:20 UTC, Atercatus commented on packages/client/views/Profile/hook/use-profile.ts
> +    const updateUserForm = async () => {
함수내에서의 함수 생성을 피해주시면 좋겠습니다.

2019-12-17 02:20 UTC, Atercatus commented on packages/client/views/Profile/hook/use-user-profile.ts
> +export const useUserProfile = () => {
hook을 개념별로 정리한 부분이 굉장히 마음에 듭니다. 다만 `use-profile.ts`와 `use-user-profile`의 명명이 너무도 유사하니 네이밍을 변경하거나, 마땅한 네이밍이 생각나지 않으신다면 애초에 분리하면 안되는 것들이니 합쳐주시길 바랍니다.

2019-12-17 02:20 UTC, Atercatus commented on packages/client/views/Profile/style.tsx
> +export const Profile = styled.div``;
빈 변수는 모두 제거해주세요

2019-12-17 02:20 UTC, Atercatus commented on packages/server/src/user/pipe/user-update-body-pipe.ts
> +    if (!username) {
이는 isEmpty에서 함께 처리되면 좋을 거 같습니다.

2019-12-17 02:32 UTC, KimJye commented on packages/client/svgs/SettingSVG/index.tsx
> +  <svg width={24} height={24} {...props}>
width, height을 props로 전달하지 않고 직접 적어준 이유가 무엇인가요?

2019-12-17 02:33 UTC, KimJye commented on packages/client/svgs/SettingSVG/index.tsx
> +      fill="#fff"
fill을 style에서 제어하지 않는 이유가 있을까요???

2019-12-17 02:34 UTC, KimJye commented on packages/client/views/Profile/hook/use-profile.ts
> +  const id = user ? user.id : 16;
16이 의미하는것이 무엇인가요?

2019-12-17 02:38 UTC, KimJye commented on packages/server/src/common/pipes/id-parser/id-parser.pipe.ts
> +    const onlyDigitRegex = RegExp(/^[0-9]*$/m);
m은 multi line을 뜻한답니다 제거부탁드립니당

2019-12-17 02:41 UTC, KimJye commented on packages/server/src/user/user.service.ts
> +    await this.userRepository.update(id, body);
id로 user를 먼저 찾고 user가 존재하면 update를 하는것이 더 안전해보입니다.

2019-12-17 02:47 UTC, riverandeye commented on packages/client/env/.env.dummy
> +AVATAR_AUTH_LAMBDA_HOST=
새로 만들었습니다.

2019-12-17 02:49 UTC, riverandeye commented on packages/client/views/Profile/action/make-mutate-avatar-pre-signed-url-action.ts
> +export const makeMutateAvatarPreSignedURLAction: Action = (path: string) => ({
네~

2019-12-17 02:55 UTC, Atercatus commented on packages/client/env/.env.dummy
> +AVATAR_AUTH_LAMBDA_HOST=
이름 변경해주세요

2019-12-17 02:56 UTC, riverandeye commented on packages/client/views/Profile/hook/use-profile.ts
> +        setUserAvatarUpdateError(true);
지울게요~

2019-12-17 03:02 UTC, riverandeye commented on packages/client/env/.env.dummy
> +AVATAR_AUTH_LAMBDA_HOST=
무엇으로 변경할까요?

2019-12-17 03:03 UTC, riverandeye commented on packages/client/views/Profile/hook/use-profile.ts
> +      if (!user) {
![image](https://user-images.githubusercontent.com/41494099/70961439-26cf7e00-20c5-11ea-96e4-7d795bf55765.png)

next 라우터는 서버사이드에서는 사용할 수 없다고 해서, 핸들러에서 사용하였습니다.

2019-12-17 03:07 UTC, riverandeye commented on packages/client/views/Profile/action/make-mutate-user-profile-action.ts
> +export const makeMutateUserProfileAction: Action = ({
액션을 명확히 구분하기 위해서 일부러 분리하였습니다.

2019-12-17 03:23 UTC, riverandeye commented on packages/server/src/user/pipe/user-update-body-pipe.ts
> +    if (!username) {
isEmpty는 3개 다 없는 경우를 보는거고, 각각이 없는 경우엔 true를 반환해야되서 이렇게 했습니다.

2019-12-17 03:23 UTC, riverandeye commented on packages/client/views/Profile/hook/use-profile.ts
> +    if (!e.target.files[0]) {
네~

2019-12-17 03:23 UTC, riverandeye commented on packages/client/views/Profile/hook/use-profile.ts
> +    const updateUserForm = async () => {
네~

2019-12-17 03:25 UTC, riverandeye commented on packages/client/views/Profile/hook/use-profile.ts
> +      if (error) {
네~

2019-12-17 03:30 UTC, riverandeye commented on packages/client/views/Profile/hook/use-profile.ts
> +      setUserProfile({
반영하였습니다~

2019-12-17 03:31 UTC, Atercatus commented on packages/client/env/.env.dummy
> +AVATAR_AUTH_LAMBDA_HOST=
먼저 고민을 해보시고 제안을 하시는게 맞는거 같습니다. 
우선 인증 부분이 존재하지않는데 AUTH가 들어있는게 다소 난해하고요
위는 PATH 인데 아래는 HOST인게 혼란을 줍니다. 한번 고민을 해보시고 서로 합의를 하는게 맞는거지 단순 일방적인 제시는 크게 도움이 될 거 같지 않습니다.

2019-12-17 03:32 UTC, riverandeye commented on packages/client/views/Profile/hook/use-user-profile.ts
> +export const useUserProfile = () => {
네~

2019-12-17 03:35 UTC, riverandeye commented on packages/client/views/Profile/style.tsx
> +export const Profile = styled.div``;
S.Profile은 최상단에 해당 페이지의 이름을 두자는 규칙을 이전에 정했기 때문에 둔겁니다. 다른건 삭제했습니다.

2019-12-17 03:37 UTC, riverandeye commented on packages/client/svgs/SettingSVG/index.tsx
> +      fill="#fff"
색깔을 변경할 이유가 없어서 그대로 뒀습니다.

2019-12-17 03:38 UTC, riverandeye commented on packages/client/views/Profile/hook/use-profile.ts
> +  const id = user ? user.id : 16;
수정했습니다.

2019-12-17 03:41 UTC, riverandeye commented on packages/client/env/.env.dummy
> +AVATAR_AUTH_LAMBDA_HOST=
뭐가 모호한지 잘 몰라서요~ 네네

2019-12-17 03:44 UTC, riverandeye commented on packages/client/env/.env.dummy
> +AVATAR_AUTH_LAMBDA_HOST=
어디가 모호한지 먼저 말씀 주셨으면 이해가 좀 쉬웠을 것 같네요.
기존에 만들어진 비디오 업로드에 사용되는 AUTH_LAMBDA_HOST는 어떤 맥락으로 작성이 된건가요? 
그리고 AVATAR_PRESIGNED_URL_PATH 는 어떤가요?

2019-12-17 03:45 UTC, riverandeye commented on packages/server/src/common/pipes/id-parser/id-parser.pipe.ts
> +    const onlyDigitRegex = RegExp(/^[0-9]*$/m);
반영했습니다.

2019-12-17 05:03 UTC, riverandeye commented on packages/server/src/user/user.service.ts
> +    await this.userRepository.update(id, body);
update 메소드는 반환값으로 업데이트된 정보를 반환하지 않습니다. 그렇기 떄문에 update 후 객체를 찾아서 반환했습니다. update 메소드는 대상이 없을 때 에러를 발생시키지 않습니다.

2019-12-17 05:04 UTC, riverandeye commented on packages/client/svgs/SettingSVG/index.tsx
> +  <svg width={24} height={24} {...props}>
현재로선 크기 변경이 불필요하여 그대로 넣었습니다 . 변경이 필요한 것 외엔 다 저렇게 되어있습니다.

2019-12-17 05:06 UTC, riverandeye commented on packages/client/views/Profile/hook/use-profile.ts
> +        error: getAvatarPreSignedUrlError,
변경했습니다~

2019-12-17 05:06 UTC, riverandeye commented on packages/client/views/Profile/action/make-mutate-user-avatar-action.ts
> +export const makeMutateUserAvatarAction: Action = ({ id, avatar }) => ({
변경했습니다~

2019-12-17 05:10 UTC, riverandeye commented on packages/client/constants.ts
> +  'https://icon-library.net/images/small-icon-images/small-icon-images-11.jpg';
변경했습니다~

2019-12-17 06:07 UTC, riverandeye commented on packages/client/env/.env.dummy
> +S3_AVATAR_PATH=
변경했습니다~

2019-12-17 06:13 UTC, riverandeye commented on packages/client/env/.env.dummy
> +AVATAR_AUTH_LAMBDA_HOST=
AVATAR_UPLOAD_PRESIGNED_URL_PATH 로 바꾸려고 하는데 어떠신가요?? 
아바타 업로드하는 Presigned URL를 요청하는 Path !

2019-12-17 06:31 UTC, hyokualexkwon approved these changes

2019-12-17 06:31 UTC, hyokualexkwon commented on packages/client/svgs/SettingSVG/index.tsx
> +  <svg width={24} height={24} {...props}>
가능하면 viewBox="0 0 24 24" 도 작성하면 좋겠네요!

2019-12-17 06:31 UTC, hyokualexkwon commented on packages/client/views/Profile/action/make-mutate-user-avatar-action.ts
> +export const makeMutateUserAvatarAction: Action = ({ id, avatar }) => ({
makeUpdateUserAvatarAction은 어때여?

2019-12-17 06:31 UTC, alexKwonIsAwesome commented on packages/client/views/Profile/action/make-mutate-user-profile-action.ts
> +export const makeMutateUserProfileAction: Action = ({
makeUpdateUserProfileAction은 어때여?

2019-12-17 06:31 UTC, alexKwonIsAwesome commented on packages/client/views/Profile/hook/use-profile.ts
> +      if (!user) {
if (!user) { router.push()}

이 내용은 initialize 외부에 있는건 어떨까요?

2019-12-17 06:31 UTC, alexKwonIsAwesome commented on packages/client/views/Profile/hook/use-profile.ts
> +  const userId = user ? user.id : 16;
여기서 16은 뭐에요?

2019-12-17 06:31 UTC, alexKwonIsAwesome commented on packages/client/views/Profile/index.tsx
> +                ></S.DescriptionInput>
self closing tag는 어떨까요?

2019-12-17 06:31 UTC, alexKwonIsAwesome commented on packages/client/views/Profile/index.tsx
> +                ></S.UserNameInput>
self closing tag는 어떨까요?

2019-12-17 06:31 UTC, alexKwonIsAwesome commented on packages/server/src/user/pipe/user-update-body-pipe.ts
> +  }
개선의 여지가 보입니다!ㅎㅎ

2019-12-17 06:31 UTC, alexKwonIsAwesome commented on packages/server/src/user/pipe/user-update-body-pipe.ts
> +      return true;
개선의 여지가 보입니다!ㅎㅎ

2019-12-17 06:31 UTC, alexKwonIsAwesome commented on packages/server/src/user/pipe/user-update-body-pipe.ts
> +      return true;
개선의 여지가 보입니다!ㅎㅎ

2019-12-17 06:31 UTC, alexKwonIsAwesome commented on packages/server/src/user/user.controller.ts
> +    @Param(null, new IdParserPipe()) id: number,
null 없이 사용할 수 있어요! 첫번째 인자에 넣으시면 되요!!!!!!!!!!!!!

2019-12-17 06:31 UTC, alexKwonIsAwesome commented on packages/server/src/user/user.controller.ts
> +    @Body(null, new UserUpdateBodyPipe()) body: UserUpdateBodyDto,
null 없이 사용할 수 있어요! 첫번째 인자에 넣으시면 되요!!!!!!!!!!!!!

2019-12-17 06:31 UTC, alexKwonIsAwesome commented on packages/server/src/user/user.controller.ts
> +      if (!user) {
개선의 여지가 보이네요!

2019-12-17 06:31 UTC, alexKwonIsAwesome commented on packages/server/src/user/user.service.ts
> +    }
개선의 여지가 보이네요!

2019-12-17 07:51 UTC, riverandeye commented on packages/client/svgs/SettingSVG/index.tsx
> +  <svg width={24} height={24} {...props}>
반영하였습니다 :)

2019-12-17 07:56 UTC, riverandeye commented on packages/client/views/Profile/action/make-mutate-user-avatar-action.ts
> +export const makeMutateUserAvatarAction: Action = ({ id, avatar }) => ({
그렇게 변경했습니다!

2019-12-17 07:59 UTC, riverandeye commented on packages/client/views/Profile/index.tsx
> +                ></S.DescriptionInput>
이전에 리뷰받았는데 반영이안됫네요.. 감사합니다.

2019-12-17 07:59 UTC, riverandeye commented on packages/client/views/Profile/index.tsx
> +                ></S.UserNameInput>
이전에 리뷰받았는데 반영이안됫네요.. 감사합니다.

2019-12-17 08:04 UTC, riverandeye commented on packages/server/src/user/pipe/user-update-body-pipe.ts
> +      return true;
반영하였습니다.

2019-12-17 08:04 UTC, riverandeye commented on packages/server/src/user/user.controller.ts
> +      if (!user) {
반영하였습니다.

2019-12-17 08:04 UTC, riverandeye commented on packages/server/src/user/user.service.ts
> +    }
반영하였습니다.

2019-12-17 08:09 UTC, riverandeye commented on packages/server/src/user/pipe/user-update-body-pipe.ts
> +      return true;
반영하였습니다.

2019-12-17 08:09 UTC, riverandeye commented on packages/client/views/Profile/hook/use-profile.ts
> +  const userId = user ? user.id : 16;
반영하였습니다.

2019-12-17 13:35 UTC, alexKwonIsAwesome commented on packages/server/src/user/user.controller.ts
> +    }
try catch를 반드시 사용해야 할까요?

2019-12-18 08:07 UTC, KimJye approved these changes
고생많으셨습니당

2019-12-18 18:59 UTC, Atercatus requested changes

2019-12-18 18:59 UTC, Atercatus commented on packages/client/views/Profile/style.tsx
> +export const Profile = styled.div``;
필요하면 두기로 했었지 반드시 만들자는 경우는 없었던 걸로 기억합니다.

2019-12-18 18:59 UTC, Atercatus commented on packages/client/views/User/hooks.ts
> +>>>>>>> 493286dabfe6a86c332e1c70704dee706fc67382
충돌이 생길 수 밖에 없는 코드네요.

2019-12-18 18:59 UTC, Atercatus commented on packages/server/src/common/pipes/id-parser/id-parser.pipe.ts
> +    const onlyDigitRegex = RegExp(/^[0-9]*$/);
그냥 `//` 사이에 두는 것과 `RegExp` 를 사용하는 것의 차이가 어떤 것 이있나요?

2019-12-18 18:59 UTC, Atercatus commented on packages/server/src/user/pipe/user-update-body-pipe.ts
> +      throw new BadRequestException('invalid User Body');
첫글자만 소문자네요?

2019-12-19 05:49 UTC, riverandeye commented on packages/server/src/user/pipe/user-update-body-pipe.ts
> +      throw new BadRequestException('invalid User Body');
수정하였습니다.

2019-12-19 05:51 UTC, riverandeye commented on packages/server/src/common/pipes/id-parser/id-parser.pipe.ts
> +    const onlyDigitRegex = RegExp(/^[0-9]*$/);
해당 부분 수정하였습니다!

2019-12-19 06:06 UTC, riverandeye commented on packages/server/src/user/user.controller.ts
> +    }
service에서 발생하는 에러를 처리하기 위해 사용하였습니다.

2019-12-20 02:38 UTC, closed without merging