Fix: 검색 결과 탭바 오류 수정
connect-foundation/2019-10 pull request #227
Opened 2019-12-21 07:25 UTC by KimJye

## 작업 내용

검색 결과 탭바가 원하는대로 나오지 않아서 관련 코드들을 수정했습니다.

## 실행 방법

https://kimjye.wedev.tv/

2019-12-21 11:14 UTC, hyokualexkwon requested changes

2019-12-21 11:14 UTC, alexKwonIsAwesome commented on packages/client/components/SearchResultsProvider/index.tsx
> +    case SET_MAP:
액션의 이름이 행동을 포함하고 있으면 좋을것 같습니다. Set option blala~?

2019-12-21 11:14 UTC, alexKwonIsAwesome commented on packages/client/views/SearchedResults/helper/make-custom-search-options.ts
> +  const optionMap = useSearchedResults().optionMap;
const { optionMap } = useSearchedResults(); 은 어때요?

2019-12-21 11:14 UTC, alexKwonIsAwesome commented on packages/client/views/SearchedResults/helper/make-custom-search-options.ts
>    optionMap.forEach((key, value) => {
map의 forEach를 돌리면` value, key` 순서 아닌가요?

2019-12-21 11:14 UTC, alexKwonIsAwesome commented on packages/client/views/SearchedResults/helper/make-custom-search-options.ts
> +    if (key.isView) {
isVisible, visible 은 어떨까요?

2019-12-21 11:32 UTC, Atercatus requested changes

2019-12-21 11:32 UTC, Atercatus commented on packages/client/components/SearchResultsProvider/index.tsx
>    const [state, dispatch] = useReducer(reducer, {
왜 한번더 객체로 감싸신건가요?

2019-12-21 11:32 UTC, Atercatus commented on packages/client/constants.ts
>  export const SET_TABS = 'setTabs';
안쓰는 변수는 그때그때 지워주세요

2019-12-21 11:32 UTC, Atercatus commented on packages/client/views/SearchedResults/helper/make-custom-search-options.ts
>    optionMap.forEach((key, value) => {
반대로 사용하셨는데 어떻게 동작하게 구현하신건가요? ㄷㄷ
key value 라는 변수보다 좀 더 명확한 이름을 사용하시면 좋을거 같습니다

2019-12-21 11:32 UTC, Atercatus commented on packages/client/views/SearchedResults/hook/use-search-tags.ts
> +  const optionMapDispatch = useSearchedResultsDispatch();
이름이 동사면 좋을 거 같습니다

2019-12-21 11:35 UTC, KimJye commented on packages/client/components/SearchResultsProvider/index.tsx
> +    case SET_MAP:
수정했습니다아ㅏㄱ

2019-12-21 11:51 UTC, KimJye commented on packages/client/components/SearchResultsProvider/index.tsx
>    const [state, dispatch] = useReducer(reducer, {
state.optionMap과 같은 형식으로 접근하려고 작성했습니다.

2019-12-21 11:57 UTC, KimJye commented on packages/client/views/SearchedResults/helper/make-custom-search-options.ts
>    optionMap.forEach((key, value) => {
ㅋㅋㅋ수정했습니다

2019-12-22 01:16 UTC, hyokualexkwon approved these changes

2019-12-22 04:06 UTC, riverandeye approved these changes

2019-12-22 06:40 UTC, Atercatus approved these changes

2019-12-22 06:43 UTC, merged