Feature/login page ui 20191115
connect-foundation/2019-10 pull request #47
Opened 2019-11-16 07:40 UTC by riverandeye

nanum-square 폰트를 적용하였습니다.
LogoSVG의 path가 svg 컴포넌트에 적절히 배치되도록 viewBox를 수정하였습니다. 
데스크탑, 모바일 환경을 모두 고려한 로그인 페이지 UI를 작성하였습니다.

2019-11-16 10:30 UTC, hyokualexkwon requested changes

2019-11-16 10:30 UTC, alexKwonIsAwesome commented on packages/client/views/Login/index.tsx
> +    <S.Container>
가장 바깥의 스타일드 컴포넌트는 Login이라고 명시하는게 좋을것 같습니다. 컴포넌트 최상단 스타일드 컴포넌트 네이밍은 이런 규칙을 따르도록 정했었습죠~

 S.Login이라고 명명하면 될것 같은데요?

2019-11-16 10:30 UTC, alexKwonIsAwesome commented on packages/client/views/Login/styles.tsx
> +  width: 31.6rem;
316px은 왜 주신건가요? 해당 텍스트는 화면 넓이에 따라서 유동적으로 변합니다. 모바일에서는 넓이 제한이 없습니다.

2019-11-16 10:30 UTC, alexKwonIsAwesome commented on packages/client/views/Login/styles.tsx
> +    width: 43rem;
그렇죠 모바일과 달리 데스크톱의 경우에는 최대 넓이가 있습니다. 좋네요!

2019-11-16 10:30 UTC, alexKwonIsAwesome commented on packages/client/views/Login/styles.tsx
> +  opacity: 75%;
디자인 스펙에 따르면 투명도는 없었습니다.

2019-11-16 10:30 UTC, alexKwonIsAwesome commented on packages/client/views/Login/styles.tsx
> +  font-size: 1.5rem;
디자인 스펙에 따르면 폰트는 16px입니다.

2019-11-16 10:30 UTC, alexKwonIsAwesome commented on packages/client/views/Login/styles.tsx
> +  height: 10rem;
높이는 컨텐츠의 길이에 따라 유동적으로 변합니다. 고정값을 주면 안됩니다.

2019-11-16 10:30 UTC, alexKwonIsAwesome commented on packages/client/views/Login/styles.tsx
> +  width: 32rem;
모바일 화면에서는 넓이가 유동적으로 변합니다. 100%가 되어야 해요. 데스크톱에서만 max-width로 넓이 제한을 주시면 됩니다.

2019-11-16 10:30 UTC, alexKwonIsAwesome commented on packages/client/views/Login/styles.tsx
> +  border-radius: 3.4rem;
완벽히 둥근 사각형에는 border-radius 100%를 주시면 됩니다.

2019-11-16 12:50 UTC, Atercatus requested changes

2019-11-16 12:50 UTC, Atercatus commented on packages/client/views/Login/styles.tsx
> +    width: 43rem;
로그인 페이지에는 버튼외에는 넓이가 고정된게 없다고 하시네요~

2019-11-16 12:50 UTC, Atercatus commented on packages/client/views/Login/styles.tsx
> +  width: 32rem;
데스크톱 화면에서만 최대 넓이를 고정하고, 모바일에서는 100%에서 화면의 좌우 여백만 20을 주어야 할 거 같습니다.

2019-11-16 14:48 UTC, riverandeye commented on packages/client/views/Login/styles.tsx
> +  border-radius: 3.4rem;
border-radius를 100%를 주니 아예 타원이 되어 버렸어요..

2019-11-16 14:59 UTC, riverandeye commented on packages/client/views/Login/index.tsx
> +    <S.Container>
주의하도록 하겠습니다.

2019-11-17 02:00 UTC, alexKwonIsAwesome commented on packages/client/views/Login/styles.tsx
> +  border-radius: 3.4rem;
ㅈㅅ합니다 그냥 가주세용! ㅋㅋ

2019-11-17 02:04 UTC, hyokualexkwon approved these changes
수고 많으셨습니다!

2019-11-17 05:05 UTC, KimJye approved these changes
확인했습니다

2019-11-18 01:44 UTC, Atercatus approved these changes

2019-11-18 01:46 UTC, merged