영상 상세 페이지 마크업 및 스타일링 작성
connect-foundation/2019-10 pull request #53
Opened 2019-11-17 10:03 UTC by alexKwonIsAwesome

영상 상세 페이지에서 그려질 내용을 작성했습니다.

2019-11-17 11:27 UTC, Atercatus requested changes
![image](https://user-images.githubusercontent.com/32104982/69006714-84fa2b80-0976-11ea-9d0b-9a489be1626b.png)
tag 의 글자가 아래쪽으로 쏠려 있는거 같아요.

이 부분은 NanumSquare 폰트 적용하면 해결되나요?

2019-11-17 11:27 UTC, Atercatus commented on packages/client/components/AppBar/styles.tsx
> +    flex-shrink: unset;
이 부분은 어떤 문제 때문에 작성하셨나요?

2019-11-17 11:27 UTC, Atercatus commented on packages/client/components/CommentItem/styles.tsx
> +    span.likes {
하트 옆에 있는 좋아요 수의 span이 조금 아래로 내려가있는거 같아요

2019-11-17 11:27 UTC, Atercatus commented on packages/client/components/CommentForm/styles.tsx
> +    font-weight: 700;
이 부분은 머지하고 수정을 해야하나요?

2019-11-17 11:27 UTC, Atercatus commented on packages/client/components/Content/index.tsx
>  interface ContentProps {
저희 생각해보니깐 lint rule에서 null 못하게 막았는데 maybe type 써도 되나요?

2019-11-17 11:27 UTC, Atercatus commented on packages/client/components/Layout/index.tsx
> +  const maxWidth = drawer ? null : 1200;
이 값의 기준은 무엇인가요?

2019-11-17 15:24 UTC, alexKwonIsAwesome commented on packages/client/components/AppBar/styles.tsx
> +    flex-shrink: unset;
기존의 display flex였던 본 컴포넌트가  display속성의 값이 block으로 바뀌면서, 기존에 적용되어 있던 flex와 관련된 속성을 취소했습니다. 혹시나 발생할지도 모를 사이드 이펙트가 우려되었습니다.

2019-11-17 15:24 UTC, alexKwonIsAwesome commented on packages/client/components/CommentItem/styles.tsx
> +    span.likes {
ㅋㅋ 그렇군요. 이부분은 폰트 적용하고 다시 봐야할것 같습니다. 본 브랜치에서는 아직 폰트가 적용되어 있지 않아서 제대로 확인이 어려울것 같아요

2019-11-17 15:24 UTC, alexKwonIsAwesome commented on packages/client/components/CommentForm/styles.tsx
> +    font-weight: 700;
그래야겠네요~

2019-11-17 15:25 UTC, riverandeye reviewed
- CommentItem
추후에 리팩토링 하실 것 같지만, return 안에서 && 로 컴포넌트의 유무를 따지니 어렵네요.. 
함수로 분리되있으면 더 이해하기 쉬울 것 같습니다.

2019-11-17 15:25 UTC, riverandeye commented on packages/client/components/VideoInfo/styles.tsx
> +  margin-bottom: 0.8rem;
요구사항에선 1rem인데, 이것도 글씨 자체의 크기에 의해 변경하신거죠??

2019-11-17 15:25 UTC, riverandeye commented on packages/client/components/CommentItem/index.tsx
> +  };
대댓글 조회를 열기만 하고 닫는 기능은 없는것 같는데 예정에 없었나보군요.

2019-11-17 15:25 UTC, riverandeye commented on packages/client/components/CommentItem/styles.tsx
> +    height: ${props => (props.reply ? '3rem' : '4rem')};
디자인에선 없는데 댓글과 대댓글의 이미지 크기를 구분하셨군요.

2019-11-17 15:25 UTC, riverandeye commented on packages/client/components/CommentItem/index.tsx
> +const CommentItem = ({
CommentItem 컴포넌트 이름이, 더 좋은 이름을 찾아야 할 것 같다고 느껴집니다. 
Video에 대한 추가적인 정보들은 VideoInfo라고 명명했듯이 CommentInfo는 어떠신가요?

2019-11-17 15:25 UTC, riverandeye commented on packages/client/components/CommentItem/index.tsx
> +          {replies.map(replyComment => {
제가 이해한 바로는 실제 데이터가 들어온다면 replies가 아니라 children 을 map 해야 될것 같은데 맞나요?

2019-11-17 15:25 UTC, riverandeye commented on packages/client/components/CommentItem/styles.tsx
> +    span.likes {
하트와 숫자가 '댓글 수정 삭제' 보다 조금 높이가 낮게 잡힌것 같아요.
button의 display를 flex로 바꾸면 조금 괜찮아지는 것 같이 보입니다.

2019-11-17 15:25 UTC, riverandeye commented on packages/client/components/CommentItem/styles.tsx
> +    user-select: none;
이런 설정을 해놓으면 사용자가 드래그 할 때 불필요한 요소를 함께 드래그 하지 않겠네요.. 되게 좋은것 같습니다.

2019-11-17 15:25 UTC, riverandeye commented on packages/client/components/CommentList/index.tsx
> +      ))}
CommentItems 안의 대댓글 컴포넌트 만드는 함수와 reply 값 말고는 다 똑같은것 같아서, 함수로 빼면 좋을 것 같습니다.

2019-11-17 15:25 UTC, riverandeye commented on packages/client/views/Video/styles.tsx
> +`;
이 부분은 import 하기 전의 Filters에 있어도 될것 같이 보이는데, 어떤 이유로 Filters/styles.tsx 에서 하지 않고 여기에서 스타일을 부여하셨나요? 왠지 이유가 있을것같아..

2019-11-17 15:25 UTC, riverandeye commented on packages/client/components/Filters/index.tsx
> +          </li>
추후에 Filter가 구현되면 여기에 들어가게 되나요?

2019-11-17 15:27 UTC, alexKwonIsAwesome commented on packages/client/components/Content/index.tsx
>  interface ContentProps {
음 props넘기지 않을때 undefined로 넘어와서 null과 관련없지 않을까요?

그리고 `lint rule에서 null 못하게 막았`이건 정확히 무슨 룰인가용?

2019-11-17 15:28 UTC, alexKwonIsAwesome commented on packages/client/components/Layout/index.tsx
> +  const maxWidth = drawer ? null : 1200;
![image](https://user-images.githubusercontent.com/17868599/69009608-3f4f5a00-099a-11ea-87b6-1065650ae4f4.png)

아 이게 그리드의 총 가로 넓이에요~ 1200px입니다.

2019-11-17 15:32 UTC, alexKwonIsAwesome commented on packages/client/components/VideoInfo/styles.tsx
> +  margin-bottom: 0.8rem;
아하 이건 더 이뻐 보여서 입니다.. 개발하면서 스펙대로 구현했는데, 구현된 결과를 디자이너가 못생겼다고 피드백을 줬습니다. 여러 값을 실험해 보다가 본 값이 가장 심미적이라고 느껴지게 되어 본 값을 작성했습니다.

2019-11-17 15:33 UTC, alexKwonIsAwesome commented on packages/client/components/CommentItem/index.tsx
> +  };
ㅋㅋ 이왕 연 댓글을 닫을 필요가 없다고 생각해서 없도록 구현했습니다/

2019-11-17 15:34 UTC, alexKwonIsAwesome commented on packages/client/components/CommentItem/styles.tsx
> +    height: ${props => (props.reply ? '3rem' : '4rem')};
![image](https://user-images.githubusercontent.com/17868599/69009681-327f3600-099b-11ea-93ee-76fa279c79ab.png)

이와 같이 유저 아바타의의 크기가 다릅니다~

2019-11-17 15:40 UTC, alexKwonIsAwesome commented on packages/client/components/CommentItem/index.tsx
> +const CommentItem = ({
음 저는 item이 더 좋은것 같은데요? Info는 단순히 정보만 있는 느낌이네여. 코멘트가 무언갈 설명하고 있지는 않잖아요? 단순히 코멘트 항목 그 자체니까요. video info는 상단의 비디오에 대해 추가적으로 설졍하고 있으니까 그부분에서 info가 적합하다고 생각해요.

2019-11-17 15:43 UTC, alexKwonIsAwesome commented on packages/client/components/CommentItem/index.tsx
> +          {replies.map(replyComment => {
자세히 보시면, 본 컴포넌트에는 replies라는 더미 데이터가 있습니다. 실제로 구현하게 되면, 본 컴포넌트 또는 상위의 가까운 위치의 컴포넌트에서 유저가 대댓글 창을 열기를 희망할때 새로 데이터를 불러오게 될꺼에요. 그래서 이름은 아~~~~무 의미가 없죠.

2019-11-17 15:44 UTC, alexKwonIsAwesome commented on packages/client/components/Filters/index.tsx
> +          </li>
이해를 못했습니다

2019-11-17 15:45 UTC, alexKwonIsAwesome commented on packages/client/views/Video/styles.tsx
> +`;
Filters는 여러군데에서 재사용할 컴포넌트라서, 사용 장소에 따라 하단의 margin이 다를 가능성이 큽니다. 그래서 해당 컴포넌트에는 margin을 주지않고, 불러다 쓰는 입장에서 margin을 부여해서 사용하고 있습니다.

2019-11-17 15:52 UTC, alexKwonIsAwesome commented on packages/client/components/CommentList/index.tsx
> +      ))}
CommentItems가 뭔가요?

2019-11-18 00:47 UTC, riverandeye commented on packages/client/components/VideoInfo/styles.tsx
> +  margin-bottom: 0.8rem;
죠습니당 ㅎㅎㅎ

2019-11-18 00:49 UTC, riverandeye commented on packages/client/components/CommentItem/index.tsx
> +const CommentItem = ({
아 제가 이 컴포넌트를 잘못 이해하고 답변했습니다. Commentitem이 Comment를 포함하고 있군여. 좋습니당.

2019-11-18 00:51 UTC, riverandeye commented on packages/client/components/CommentList/index.tsx
> +      ))}
CommentItems > ComentItem 오타입니다

2019-11-18 01:39 UTC, KimJye approved these changes
엑설런트

2019-11-18 02:07 UTC, alexKwonIsAwesome commented on packages/client/components/CommentList/index.tsx
> +      ))}
공통화 하려고했는데, 리액트 컴포넌트가 recursive하게 import될때 undefined가 되는 이슈가 발생하네요. 해당 이슈를 해결하고 추후에 공통화 하도록 하겠습니다.

2019-11-18 02:13 UTC, Atercatus approved these changes

2019-11-18 02:16 UTC, riverandeye approved these changes

2019-11-18 02:20 UTC, merged