회원가입 Form 작성 페이지 UI 작성
connect-foundation/2019-10 pull request #59
Opened 2019-11-18 10:14 UTC by riverandeye

신규 회원가입 시 추가 정보를 제출하는 페이지를 작성하였습니다.
Nickname과 체크박스가 입력되지 않을 시 버튼이 활성화되지 않는 기능을 추가하였습니다.

2019-11-19 01:44 UTC, alexKwonIsAwesome commented on packages/client/pages/loginform.tsx
> +export { default } from '../views/LoginForm';
사용자는 `/loginform`이라는 경로에 접근하게 될텐데, path가 semantic하다고 생각되지 않습니다. 

이제보니 인증페이지도 `/login` 경로에서 접근하게 되는데, 회원가입 기능도 한번에 하는 페이지임을 고려하면 충분히 의미를 담고 있는것 같지 않습니다.

차라리 인증 페이지는 `/auth`, 그리고 회원가입 양식 페이지는 `/auth/additional-info` 와 같은 path로 표현하는건 어떨까요?

2019-11-19 01:44 UTC, alexKwonIsAwesome commented on packages/client/views/LoginForm/index.tsx
> +  const [input, setInput] = useState({
form의 데이터를 다루는 state같은데, input이라는 이름이 사용되고 있네요. form은 input만을 포함하는게 아닐텐데 조금 더 포괄적인 이름이 없을까요?

2019-11-19 01:44 UTC, alexKwonIsAwesome commented on packages/client/views/LoginForm/index.tsx
> +  });
소개 항목에 작성한 데이터는 어디서 관리되고 있나요?

2019-11-19 01:44 UTC, alexKwonIsAwesome commented on packages/client/views/LoginForm/index.tsx
> +              <label htmlFor="introduction">소개</label>
db entity에 따르면, 유저 소개는 description이라는 이름으로 사용되고 있는데, 같은 이름을 쓰는게 더 좋지 않을까요?

2019-11-19 01:44 UTC, alexKwonIsAwesome commented on packages/client/views/LoginForm/index.tsx
> +              <label htmlFor="nickname">
db entity에서 사용자 닉네임은 username이라는 이름으로 사용하고 있는데, 같은 이름을 쓰는게 더 좋지 않을까요?

2019-11-19 01:44 UTC, alexKwonIsAwesome commented on packages/client/views/LoginForm/index.tsx
> +                닉네임<S.RequireMark></S.RequireMark>
RequireMark는 children을 넘기지 않는다면 self closing tag를 쓰는게 더 좋지 않을까요? `<RequireMark/>

2019-11-19 01:44 UTC, alexKwonIsAwesome commented on packages/client/views/LoginForm/index.tsx
> +  const handleNickname = e => {
저는 이벤트 핸들러에는 이벤트 이름이 들어가면 좋다는 생각을 하고 있는데요, 예를 들어 handleUsernameChange와 같이 말이죠. 왜냐하면 Username에 또 다른 이벤트를 감지하게 되면 추가로 핸들러가 생길 수 있잖아요? handleUsernameClick과 같이 말이죠. 한번 고려해주시면 감사하겠습니다~

2019-11-19 01:44 UTC, alexKwonIsAwesome commented on packages/client/views/LoginForm/index.tsx
> +            ></input>
self closing tag!

2019-11-19 01:44 UTC, alexKwonIsAwesome commented on packages/client/views/LoginForm/index.tsx
> +            <S.InputInfo>
InputInfo라는 이름을 사용하셨는데, textarea를 설명하게 된다면 TextareaInfo가 되어야 하지 않을까요? 범용적인 이름을 사용해야 할 것 같습니다. label 정보를 담고 있으니 `Label`이라고 명명하는건 어떨까요?

2019-11-19 01:44 UTC, alexKwonIsAwesome commented on packages/client/views/LoginForm/index.tsx
> +          <S.Input>
Input이라는 이름을 사용하셨는데, textarea를 설명하게 된다면 Textarea가 되어야 하지 않을까요? 범용적인 이름을 사용해야 할것 같습니다. form에 포함되어있는 입력 항목들을 의미한다면`Item`이라고 명명하는건 어떨까요?

2019-11-19 01:44 UTC, alexKwonIsAwesome commented on packages/client/views/LoginForm/index.tsx
> +              <input onClick={handlecheck} type="checkbox" id="agree"></input>
self closing tag

2019-11-19 01:44 UTC, alexKwonIsAwesome commented on packages/client/views/LoginForm/index.tsx
> +              <input onClick={handlecheck} type="checkbox" id="agree"></input>
handlecheck? 이름만 봐서 무엇을 체크하는지 알 수 있나요? checkbox 또는 agree라는 이름이 들어가야하지 않을까요?

그리고 왜 여기는 camelcase가 아닌가요?

2019-11-19 01:44 UTC, alexKwonIsAwesome commented on packages/client/views/LoginForm/index.tsx
> +            <button disabled={active}>가입하기</button>
양식 제출 버튼의 disabled 여부가 단순히 양식이 채워졌는지 여부로만 검사하고있는데, 양식이 제출되어서 서버에 요청이 보내고 응답이 오기 전까지 disabled 하는 것은 어떻게 처리해야할까요?

2019-11-19 01:58 UTC, riverandeye commented on packages/client/pages/loginform.tsx
> +export { default } from '../views/LoginForm';
정말 좋은 의견이라고 생각합니다

2019-11-19 04:51 UTC, KimJye approved these changes
확인했습니다

2019-11-19 06:18 UTC, riverandeye commented on packages/client/views/LoginForm/index.tsx
> +  });
반영했습니다~

2019-11-19 06:19 UTC, riverandeye commented on packages/client/views/LoginForm/index.tsx
> +              <label htmlFor="introduction">소개</label>
반영하였습니다

2019-11-19 06:19 UTC, riverandeye commented on packages/client/views/LoginForm/index.tsx
> +              <label htmlFor="nickname">
반영했습니다~

2019-11-19 06:20 UTC, riverandeye commented on packages/client/views/LoginForm/index.tsx
> +            <S.InputInfo>
좋은 의견 감사합니다~ 반영했습니다!

2019-11-19 06:27 UTC, riverandeye commented on packages/client/views/LoginForm/index.tsx
> +          <S.Input>
역시 좋은 생각이에요 ㅎㅎ

2019-11-19 06:29 UTC, riverandeye commented on packages/client/views/LoginForm/index.tsx
> +              <input onClick={handlecheck} type="checkbox" id="agree"></input>
반영하였습니다~

2019-11-19 06:36 UTC, riverandeye commented on packages/client/views/LoginForm/index.tsx
> +  const handleNickname = e => {
좋은 의견이에요! 수렴하겠습니다~

2019-11-19 06:37 UTC, riverandeye commented on packages/client/views/LoginForm/index.tsx
> +                닉네임<S.RequireMark></S.RequireMark>
좋은 의견이에요! 수렴하겠습니다~

2019-11-19 06:37 UTC, riverandeye commented on packages/client/views/LoginForm/index.tsx
> +            ></input>
ㅎㅎㅎ수렴하겠습니다~

2019-11-19 06:37 UTC, riverandeye commented on packages/client/views/LoginForm/index.tsx
> +              <input onClick={handlecheck} type="checkbox" id="agree"></input>
ㅎㅎ수렴하겠습니다~

2019-11-19 06:41 UTC, riverandeye commented on packages/client/views/LoginForm/index.tsx
> +  const [input, setInput] = useState({
formData로 가겠습니다~

2019-11-19 07:25 UTC, riverandeye commented on packages/client/views/LoginForm/index.tsx
> +            <button disabled={active}>가입하기</button>
수렴하였습니다~

2019-11-19 12:11 UTC, Atercatus requested changes
서비스약관 추가와, 가입하기 버튼에 cursor 속성을 변경해야 할 거 같습니다.

2019-11-19 12:11 UTC, Atercatus commented on packages/client/constants.ts
> +  introduction: 1500,
entity 에서는 3000인데 여기선 1500 인건 한글을 생각해서 인가여

2019-11-19 12:11 UTC, Atercatus commented on packages/client/views/Auth/index.tsx
> +const Auth: React.FunctionComponent = () => {
아래에는 `AuthenticateLink`라고 상세히 묘사 했지만 여기선 `Auth` 라고 하신 이유가 있나요? 
좀 더 상세한 의미가 좋을 거같은데 어떻게 생각하세요?

2019-11-19 12:11 UTC, Atercatus commented on packages/client/views/SignUp/index.tsx
> +const AuthForm: React.FunctionComponent = () => {
`SignUp` 페이지에 있는 `AuthForm`은 의미가 명확하지 않네요.
`SignUpForm`을 말씀하시는 건가요

2019-11-19 12:11 UTC, Atercatus commented on packages/client/views/SignUp/index.tsx
> +  const [formData, setInput] = useState({
상태명은 `formData` 인데 그에 따른 함수명은 `setInput`이네요. 
의미상으로 좀 더 통일성을 가지면 좋을거 같습니다.

2019-11-19 12:11 UTC, Atercatus commented on packages/client/views/SignUp/index.tsx
> +    setInput({ ...formData, agree: !formData.agree });
의미상으로 너무 난해합니다.
`agree`에 `!formData.agree` 을 대입하는 표현은 설명을 하지않으면 도무지 해석이 불가능합니다.

2019-11-19 12:11 UTC, Atercatus commented on packages/client/views/SignUp/index.tsx
> +  const [sending, setSending] = useState(false);
다른 표현이 좋을 거 같습니다. boolean 을 `isXXX`로 네이밍하기로 하셨다면 통일을 하거나 좀 더 명확한 표현이 좋겠네요

2019-11-19 12:11 UTC, Atercatus commented on packages/client/views/SignUp/index.tsx
> +  const isButtonDisabled = sending ? true : isFormFilled;
너무 겉멋이 들어간 코드입니다. 짧게 만들기 위해 가독성을 포기해버린 코드입니다.
짧은 코드가 가독성이 높은 코드가 아니라 그냥 읽었을 때 의도가 보이는 코드가 좋은 코드입니다.  조건문에 대해서 삼항 연산자를 겹쳐 쓰면 종종 이런 의도가 보이지 않는 코드가 발생합니다. 

```javascript
function checkFormVerified() {
  return !(formData.isAgree && formData.username);
}
const isButtonDisabled = checkFormVerified() && isSending;
```
 와 같은 방법을 이용해 주세요

2019-11-19 14:18 UTC, alexKwonIsAwesome commented on packages/client/views/SignUp/index.tsx
> +  const [formData, setInput] = useState({
이 부분은 리액트 관습에 따르면, formData => setFormData 라고 지으면 좋을것 같네여~

2019-11-20 00:45 UTC, riverandeye commented on packages/client/constants.ts
> +  introduction: 1500,
네 맞아요~

2019-11-20 00:49 UTC, riverandeye commented on packages/client/views/Auth/index.tsx
> +const Auth: React.FunctionComponent = () => {
폴더 이름이랑 똑같이 설정하려고 그렇게 했습니다.

2019-11-20 00:50 UTC, riverandeye commented on packages/client/views/SignUp/index.tsx
> +const AuthForm: React.FunctionComponent = () => {
네네 반영하였습니다.

2019-11-20 00:50 UTC, riverandeye commented on packages/client/views/SignUp/index.tsx
> +  const [formData, setInput] = useState({
반영하였습니다

2019-11-20 00:52 UTC, riverandeye commented on packages/client/views/SignUp/index.tsx
> +  const [sending, setSending] = useState(false);
반영하였습니다~

2019-11-20 01:14 UTC, hyokualexkwon commented on packages/client/views/SignUp/index.tsx
> +const AuthForm: React.FunctionComponent = () => {
컴포넌트 이름이 파일 디렉토리 이름을 따라가면 좋을것 같아요! `SignUp`과 같이 말이죠~

2019-11-20 01:14 UTC, hyokualexkwon commented on packages/client/views/SignUp/index.tsx
> +              type={'text'}
type="text" 와 같이 작성하는게 더 자연스러울것 같아요!

2019-11-20 01:26 UTC, riverandeye commented on packages/client/views/SignUp/index.tsx
> +    setInput({ ...formData, agree: !formData.agree });
반영하였습니다~

2019-11-20 01:27 UTC, riverandeye commented on packages/client/views/SignUp/index.tsx
> +  const isButtonDisabled = sending ? true : isFormFilled;
반영하였습니다~

2019-11-20 01:27 UTC, riverandeye commented on packages/client/views/SignUp/index.tsx
> +const AuthForm: React.FunctionComponent = () => {
반영하였습니다~

2019-11-20 01:28 UTC, riverandeye commented on packages/client/views/SignUp/index.tsx
> +              type={'text'}
반영하였습니다~

2019-11-20 06:20 UTC, alexKwonIsAwesome commented on packages/client/views/SignUp/index.tsx
> +  const handleIntroduction = e => {
왜 description의 핸들러가 handleIntroduction인가요? 같은 네이밍을 사용하는것이 덜 헷갈리지 않을까요?

2019-11-20 06:20 UTC, alexKwonIsAwesome commented on packages/client/views/SignUp/index.tsx
> +              <label htmlFor="username">
htmlFor를 사용하셨는데, 가리키는 input이 없어 보이는데요? for가 가르키는것은 어떤 input의 id를 가리키는 것으로 알고 있어요. 닉네임을 작성하는 input에 id="username"을 작성하셔야할것 같아요

2019-11-20 06:20 UTC, alexKwonIsAwesome commented on packages/client/views/SignUp/index.tsx
> +  const handleUsername = e => {
input 과 textarea 마다 핸들러를 별도로 작성하셨는데, name을 활용해서 조금 더 간결하게 쓸 수 있어요

```
const handleChange = e => {
  const { name, value } = e.target;
  setFormData({
    ...formData,
    [name]: value
  });
}
```

이런 방법은 어떨까요?

2019-11-20 06:22 UTC, riverandeye commented on packages/client/views/SignUp/index.tsx
> +  const handleUsername = e => {
오오 한번 시도해보겠습니다.

2019-11-20 06:26 UTC, riverandeye commented on packages/client/views/SignUp/index.tsx
> +              <label htmlFor="username">
리팩토링하는 과중에 지워버렸네요 다시 반영하겠습니다.

2019-11-20 07:04 UTC, hyokualexkwon approved these changes
고생 많으셨네요!  👍

2019-11-20 07:06 UTC, riverandeye commented
> 고생 많으셨네요! 👍

덕분에 많이 배웁니다 ㅠ.ㅠ

2019-11-21 02:18 UTC, Atercatus approved these changes

2019-11-21 02:19 UTC, merged