AppBar 부분 검색 UI 및 라우팅
connect-foundation/2019-10 pull request #64
Opened 2019-11-19 04:38 UTC by KimJye

모바일에서, 검색 아이콘을 눌렀을 때 검색이 활성화됩니다.
모바일, 데스크탑 둘다 검색을 했을떄,  검색 결과 화면으로 라우팅됩니다.
아직 검색 결과 화면은 구현하지 않아서, AppBar부분의 검색 UI와 라우팅 부분만 봐주시면 됩니다.
감사합니다

2019-11-19 04:41 UTC, KimJye commented on packages/client/views/Search/index.tsx
> +        </S.Title>
이하 아직 미구현된 부분입니다. 앞으로는 리뷰가 필요한 부분만 올리겠습니다.

2019-11-19 04:41 UTC, KimJye commented on packages/client/views/Search/styles.tsx
> +import styled from 'styled-components';
아직 미구현된 부분입니다. 앞으로는 리뷰가 필요한 부분만 올리겠습니다.

2019-11-19 05:01 UTC, Atercatus requested changes

2019-11-19 05:01 UTC, Atercatus commented on packages/client/components/Search/index.tsx
> +  inActive: () => void;
함수의 네이밍은 동사가 되면 좋을거 같습니다.

2019-11-19 05:01 UTC, Atercatus commented on packages/client/components/Search/index.tsx
> +export const Search: React.FunctionComponent<Searchprops> = props => {
매개변수를 인터페이스로 정의한김에 destructing을 사용해서 `props`를 중복해서 쓰지 않도록 하면 더 깔끔해질거 같습니다.

2019-11-19 05:15 UTC, KimJye commented on packages/client/components/Search/index.tsx
> +  inActive: () => void;
넵

2019-11-19 09:03 UTC, Atercatus requested changes

2019-11-19 09:03 UTC, Atercatus commented on packages/client/components/AppBar/index.tsx
> +        <Search deActive={handleActiveSearchBar} isActive={isActiveSearchBar} />
`deActive` 가 하나의 동사라면 `deactive` 가 맞는거 같아요

2019-11-19 11:59 UTC, Atercatus requested changes

2019-11-19 11:59 UTC, Atercatus commented on packages/client/components/AppBar/index.tsx
> +        <Search deactive={handleActiveSearchBar} isActive={isActiveSearchBar} />
`deactive ` 란 말은 없고  `deactivate` 가 옳은 표현 이라고 하네요 ㅠㅠ

2019-11-20 02:20 UTC, hyokualexkwon commented on packages/client/svgs/SearchSVG/index.tsx
> +  <svg width={20} height={20} {...props}>
SearchSVG의 크기가 고정되어서 재사용이 어려워졌네요.
![image](https://user-images.githubusercontent.com/17868599/69200666-28b62800-0b7f-11ea-9816-06a7cc52bb2c.png)
 본 UI에서는 SearchSVG가 가로세로 24px이어야 합니다.

2019-11-20 02:20 UTC, hyokualexkwon commented on packages/client/views/Search/index.tsx
> +        </S.Title>
아직 스케폴딩이니까 올리셔도 괜찮을것 같아요~

2019-11-20 02:20 UTC, hyokualexkwon commented on packages/client/components/Search/index.tsx
> +        <S.Input placeholder="검색" onKeyPress={sendQuery}></S.Input>
![image](https://user-images.githubusercontent.com/17868599/69200852-cc073d00-0b7f-11ea-82f6-0f38b0d52221.png)
 input의 영역이 전체 넓이를 포함하고 있지 않습니다.

2019-11-20 02:20 UTC, hyokualexkwon commented on packages/client/components/Search/styles.tsx
> +  font-size: 1.8rem;
디자인 스펙 상 16px입니다.

2019-11-20 02:20 UTC, hyokualexkwon commented on packages/client/components/Search/styles.tsx
> +  padding-top: 0.2rem;
이 값을 왜 주신거에요?

2019-11-20 02:20 UTC, hyokualexkwon commented on packages/client/components/Search/styles.tsx
> +  padding-bottom: 0.2rem;
이 값을 왜 주신거에요?

2019-11-20 02:20 UTC, hyokualexkwon commented on packages/client/components/Search/index.tsx
> +      <S.InputLayer isActive={isActive}>
마크업 구성을
```
<S.Input>
  <SearchSVG />
  <input />
</S.Input>
```

이런식으로 가져가는건 어떨까요? input엘리먼트에 대해 별도 props로 조작하는 부분이 없으니 따로 styled-component로 빼지 않고 간결하게 작성 할 수 있을것 같아요.

2019-11-20 02:20 UTC, hyokualexkwon commented on packages/client/components/Search/index.tsx
> +    if (e.key === 'Enter') {
모바일에서 테스트 했을때에도 잘되나용?

2019-11-20 02:20 UTC, hyokualexkwon commented on packages/client/components/Search/index.tsx
> +import Router from 'next/router';
저희 Router대신에 useRouter를 사용하는건 어떨까요? 저희 앱에서 hook을 사용할 수 있으면 최대한 사용하는게 좋을것 같아서요.

2019-11-20 02:20 UTC, hyokualexkwon commented on packages/client/components/AppBar/index.tsx
> +  const [isActiveSearchBar, setActiveSearchBar] = useState(false);
영미권 사람들은 헷갈려할것 같아요. Is the search bar active?  라고 물어볼것 같은데요? isSearchBarActive가 더 낫지 않을까요?

2019-11-20 02:20 UTC, alexKwonIsAwesome commented on packages/client/components/Search/index.tsx
> +import React from 'react';
Search라는 이름보다는 SearchBar가 조금 더 ui를 잘 드러내는 네이밍일것 같습니다!

2019-11-20 03:12 UTC, riverandeye approved these changes
라우터를 이용해서 핵심 기능을 적절히 구현한 것으로 보여 Approve 하겠습니다.
리뷰한 부분만 한번 살펴주시면 좋을것 같아요.

2019-11-20 03:12 UTC, riverandeye commented on packages/client/components/Search/index.tsx
> +    if (e.key === 'Enter') {
제가 확인해봤는데 입력 버튼 누르면 검색 페이지 전환 잘 됩니다.

2019-11-20 03:12 UTC, riverandeye commented on packages/client/components/Search/index.tsx
> +        <S.Input placeholder="검색" onKeyPress={sendQuery}></S.Input>
모바일 환경에서도 입력한 글자가 끝까지 나타나지 않는 오류가 생깁니다.

2019-11-20 03:12 UTC, riverandeye commented on packages/client/components/Search/styles.tsx
> +  margin-left: 1.17rem;
디자인 스펙상 1rem이 맞는것 같습니다.

2019-11-20 07:44 UTC, KimJye commented on packages/client/components/Search/index.tsx
> +    if (e.key === 'Enter') {
> 모바일에서 테스트 했을때에도 잘되나용?

넹~

2019-11-21 02:25 UTC, Atercatus requested changes

2019-11-21 02:25 UTC, Atercatus commented on packages/client/components/AppBar/index.tsx
> +  const handleActiveSearchBar = () => {
이 부분만 수정하시면 될 거같아욥

2019-11-21 04:15 UTC, alexKwonIsAwesome commented on packages/client/components/AppBar/index.tsx
> +  const [isSearchBarActive, SearchBarActive] = useState(false);
`[isSearchBarActive, setSearchBarActive]` 라고 되어야 할것 같은데요?

2019-11-21 04:29 UTC, KimJye commented on packages/client/components/AppBar/index.tsx
> +  const [isSearchBarActive, SearchBarActive] = useState(false);
뜨헉

2019-11-21 06:57 UTC, Atercatus requested changes

2019-11-21 06:57 UTC, Atercatus commented on packages/client/components/SearchBar/index.tsx
> +interface SearchBarprops {
`SearchBarProps`로 오타가 난 거 같아요.

2019-11-21 06:57 UTC, Atercatus commented on packages/client/components/SearchBar/index.tsx
> +        <SearchSVG width="20" height="20" viewBox="0 0 20 20" />
`<SearchSVG width={23} height={24} />` 위에는 이런식으로 되어있는데 통일이 되면 좋을 거 같아요.

2019-11-21 07:17 UTC, KimJye commented on packages/client/components/SearchBar/index.tsx
> +        <SearchSVG width="20" height="20" viewBox="0 0 20 20" />
> `<SearchSVG width={23} height={24} />` 위에는 이런식으로 되어있는데 통일이 되면 좋을 거 같아요.

viewBox는 어떻게할수있을까요??ㅠㅠ

2019-11-21 07:21 UTC, Atercatus requested changes

2019-11-21 07:21 UTC, Atercatus commented on packages/client/components/SearchBar/index.tsx
> +        <SearchSVG width="20" height="20" viewBox="0 0 20 20" />
```
 <SearchSVG width={20} height={20} viewBox={"0 0 20 20"} />
```
이렇게는 안되나여?

2019-11-21 07:32 UTC, Atercatus approved these changes

2019-11-21 07:32 UTC, hyokualexkwon approved these changes

2019-11-21 07:45 UTC, merged