유저 페이지 마크업 및 스타일 작성
connect-foundation/2019-10 pull request #68
Opened 2019-11-19 15:02 UTC by alexKwonIsAwesome

유저 정보를 조회할 수 있는 유저 페이지를 작성했습니다.

2019-11-20 07:43 UTC, riverandeye commented on packages/client/views/User/index.tsx
> +    <Layout drawer={false}>
데스크톱 유저 상세 페이지에서 Drawer가 없는데, 없는게 더 예뻐보여서 그렇게 하셨나요?
그리고 Drawer가 없는 경우에 Appbar의 Logo와 Button들의 위치가 변경되는데, 저는 그냥 변경되지 않는것도 예쁘다고 생각하는데 어떻게 보시나요?

2019-11-20 07:43 UTC, riverandeye commented on packages/client/views/User/index.tsx
> +  }, []);
추후에 테스트(?)를 위해서 reducer 함수를 빼주면 좋을것 같아요~~
utils.ts를 만들어서 거기에 두는건 어떨까요?

2019-11-20 07:43 UTC, riverandeye commented on packages/client/components/UserProfile/styles.tsx
> +    color: white;
모바일 환경에서 username에 해당하는 부분은 화면의 중앙에 배치되어야 합니다. 현재는 왼쪽에 붙어있는 것으로 보입니다. 

![image](https://user-images.githubusercontent.com/41494099/69218744-b102f000-0bb4-11ea-9360-3a10bd15c88d.png)


이부분과

![image](https://user-images.githubusercontent.com/41494099/69218756-b6f8d100-0bb4-11ea-8aee-ab0f46381604.png)


이부분이 다릅니다.

2019-11-20 07:43 UTC, riverandeye commented on packages/client/components/UserProfile/styles.tsx
> +    left: -2rem;
요구사항과 달리 모바일 환경에서 UserProfile과 업로드한 동영상을 구분짓는 하얀 선이 가로 전체에 그어지게 됩니다. 

![image](https://user-images.githubusercontent.com/41494099/69218672-916bc780-0bb4-11ea-9bf7-fa148e9c5a72.png)

이부분과

![image](https://user-images.githubusercontent.com/41494099/69218692-992b6c00-0bb4-11ea-86d5-9c1fa01a86d4.png)


이부분이 다릅니다.

2019-11-20 07:43 UTC, riverandeye requested changes
혹시, 이건 개인적인 의견이지만, 개인 회원에 접근할 때 /users/:id로 접근하는데, 혹시 /:githubId 로 접근하게끔 할 생각 없으신가요? 그렇게 하면 접근성이 더 좋을것 같아서요!

2019-11-20 09:06 UTC, KimJye commented on packages/client/components/VideoItem/styles.tsx
![image](https://user-images.githubusercontent.com/33201628/69224682-54a5cd80-0bc0-11ea-8f27-9ad86493a8d8.png)
동영상 리스트가 오른쪽에 딱 붙어있는것같아요ㅠㅠ

2019-11-21 08:24 UTC, alexKwonIsAwesome commented on packages/client/components/UserProfile/styles.tsx
> +    left: -2rem;
아 죄송합니다 디자인이 조금 바뀌었습니다. 현재 반영된 내용을 적용하려고 합니다.

2019-11-21 08:24 UTC, alexKwonIsAwesome commented on packages/client/components/UserProfile/styles.tsx
> +    color: white;
ㅎㅎ 디자인을 변경했습니다.

2019-11-21 08:24 UTC, alexKwonIsAwesome commented on packages/client/components/VideoItem/styles.tsx
제보 감사합니다. 반반을 차지하도록 수정했습니다.

2019-11-21 08:24 UTC, alexKwonIsAwesome commented on packages/client/views/User/index.tsx
> +    <Layout drawer={false}>
drawer가 없는게 더 자연스러워 보였습니다~

그리고 drawer가 없는 경우에는  max-width를 적용해야 하기 때문에 위치가 변경되어 보일 수 있습니다. 자연스러운 행동입니다.

2019-11-21 08:34 UTC, KimJye approved these changes
고생하셨습니다

2019-11-21 12:53 UTC, riverandeye approved these changes

2019-11-22 04:37 UTC, Atercatus approved these changes

2019-11-22 04:38 UTC, merged