영상 리스트 API작성
connect-foundation/2019-10 pull request #71
Opened 2019-11-21 08:09 UTC by alexKwonIsAwesome

영상 리스트를 조회할 수 있는 API를 작성했습니다.

page 쿼리를 통해 페이지네이션을 요청할 수 있습니다.
sort 쿼리를 통해, 최신 순 인기 순 정렬을 할 수 있습니다. 현재 인기 순 정렬은 조회 수만을 기준으로 정렬합니다. 향후에 댓글 수, 좋아요 수, 조회 수를 종합적으로 고려하여 정렬해야 합니다.

인기 순 정렬 시, 일주일, 한달, 일년, 전체의 날짜 필터링은 아직 적용되지 않았습니다. 추후에 작업할 예정입니다.

2019-11-21 08:44 UTC, KimJye commented on packages/typeorm/src/entity/user.entity.ts
>    @ManyToMany(
👍

2019-11-21 08:45 UTC, KimJye commented on packages/server/src/video/video.dto.ts
> +  sort: string;
이 둘은 항상 필수로 넘어오는 값들인가요??

2019-11-21 08:52 UTC, KimJye commented on packages/server/src/common/pipes/getVideosQueryPipe.ts
> +export class GetVideosQueryPipe implements PipeTransform {
혹시 이 클래스에대해서 설명 좀 해줄수있나요??

2019-11-21 09:11 UTC, alexKwonIsAwesome commented on packages/server/src/common/pipes/getVideosQueryPipe.ts
> +export class GetVideosQueryPipe implements PipeTransform {
컨트롤러에 넘어오는 값들에 대해 validation 로직을 담고 있습니다!

2019-11-21 09:11 UTC, alexKwonIsAwesome commented on packages/server/src/video/video.dto.ts
> +  sort: string;
컨트롤러 입장에서는 항상 넘겨 받고 있습니다. 실제 query에 page, sort가 없더라도, pipe가 page와 sort의 기본값을 controller에 넘기도록 작성했습니다.

2019-11-21 09:12 UTC, KimJye approved these changes
확인했습니다

2019-11-21 09:26 UTC, Atercatus requested changes

2019-11-21 09:26 UTC, Atercatus commented on packages/server/src/common/pipes/getVideosQueryPipe.ts
> +    { page, sort }: { page: string; sort: string },
class로 빼면 좋을 거 같습니다.

2019-11-21 09:26 UTC, Atercatus commented on packages/server/src/common/pipes/getVideosQueryPipe.ts
> +    const value = {
이해하기 쉽게 변수로 빼면 좋을 거 같습니다.

2019-11-21 09:26 UTC, Atercatus commented on packages/server/src/common/pipes/getVideosQueryPipe.ts
> +      } else {
early-return 으로 해서 깊이가 줄어들면 보기 좋을 거 같습니다.

2019-11-21 09:26 UTC, Atercatus commented on packages/server/src/common/pipes/getVideosQueryPipe.ts
> +    return !isNaN(parsedPage) && parsedPage > 0;
한번 찾아보겠습니다..

2019-11-21 09:26 UTC, Atercatus commented on packages/server/src/common/pipes/getVideosQueryPipe.ts
> +    return sort === 'latest' || sort === 'popular';
이것도 상수로 빼면 좋을 거 같습니다.

2019-11-21 09:26 UTC, Atercatus commented on packages/server/src/video/video.controller.ts
> +    @Query(GetVideosQueryPipe) getVideosQueryDto: GetVideosQueryDto,
파이프가 여기 들어가 있는게 이상한거 같아요.
`@UsePipes` 데코레이터를 쓰지 않아도 동작하나요?

2019-11-21 09:26 UTC, Atercatus commented on packages/server/src/video/video.service.ts
> +  public async findVideos({ page, sort }): Promise<Video[]> {
클래스로 빼면 좋을 거 같습니다. ㅎㅎ;;;

2019-11-21 09:26 UTC, Atercatus commented on packages/server/src/video/video.service.ts
> +    if (sort === 'latest') {
내 맴 알져? ㅎㅎ

2019-11-22 04:42 UTC, Atercatus approved these changes

2019-11-22 11:55 UTC, riverandeye approved these changes

2019-11-22 11:55 UTC, merged