검색 결과 화면 및 검색 결과 없는 화면 구현
connect-foundation/2019-10 pull request #79
Opened 2019-11-22 07:26 UTC by KimJye

검색 결과 화면은, 더보기 부분 디자인이 나오지않아서 임의로 제가 구현해보았습니다.
검색 결과 없는 화면은 모바일 디자인이 없어서 임의로 제가 구현해보았습니다.

2019-11-23 09:42 UTC, Atercatus requested changes
![image](https://user-images.githubusercontent.com/32104982/69476722-e744a780-0e20-11ea-9f25-de0833d26d27.png)

주석을 지웠을 때 제대로 나오지않네요.
구현하신 페이지를 제 로컬에서 돌릴 수 있는 방법을 알 수 있으면 좋겠어요.

2019-11-24 02:53 UTC, KimJye commented on packages/client/views/Search/index.tsx
> +          </Grid>
이 부분은 검색 결과가 없을때 화면입니다. 현재는 검색 결과가 없는 화면으로 설정해두었습니다. 
검색 결과가 있을때 화면은 150~ 152줄을 주석처리하고 밑에 주석처리된 부분을 주석해제하시면 됩니다.

2019-11-24 02:55 UTC, KimJye commented
> ![image](https://user-images.githubusercontent.com/32104982/69476722-e744a780-0e20-11ea-9f25-de0833d26d27.png)
> 
> 주석을 지웠을 때 제대로 나오지않네요.
> 구현하신 페이지를 제 로컬에서 돌릴 수 있는 방법을 알 수 있으면 좋겠어요.

수정했습니다~


> ![image](https://user-images.githubusercontent.com/32104982/69476722-e744a780-0e20-11ea-9f25-de0833d26d27.png)
> 
> 주석을 지웠을 때 제대로 나오지않네요.
> 구현하신 페이지를 제 로컬에서 돌릴 수 있는 방법을 알 수 있으면 좋겠어요.

수정했습니다~
현재는 검색 결과가 없는 화면으로 설정해두었습니다.
검색 결과가 있을때 화면은 150~ 152줄을 주석처리하고 밑에 주석처리된 부분을 주석해제하시면 됩니다.

2019-11-25 03:43 UTC, riverandeye approved these changes

2019-11-25 08:23 UTC, alexKwonIsAwesome commented
디자인이 많이 변경되어서, 반영 한 후에 새 PR을 작성하는건 어떨까요?

2019-11-29 04:32 UTC, closed without merging