로그인 UI Grid 적용
connect-foundation/2019-10 pull request #91
Opened 2019-11-25 09:46 UTC by riverandeye

로그인 UI에 Grid를 적용하여 리팩토링 하였습니다.

2019-12-01 11:02 UTC, Atercatus requested changes
혁우님이 다시 한번 확인 해달라고 하십니다. 월요일에 같이 말씀을 나눠봐요

2019-12-02 02:01 UTC, hyokualexkwon commented on packages/client/views/SignUp/styles.tsx
> +  max-width: 58.8rem;
여기에는 max-width를 주면 안되겠죠?

2019-12-02 02:01 UTC, alexKwonIsAwesome commented on packages/client/views/SignUp/styles.tsx
> -  max-width: 58.8rem;
max-width 1200px을 줘야겠죠?

![image](https://user-images.githubusercontent.com/17868599/69925352-09aa8500-14f3-11ea-84df-d9ae8b83c99b.png)

2019-12-02 02:01 UTC, alexKwonIsAwesome commented on packages/client/views/SignUp/index.tsx
> +        <Grid item xs={12} md={8}>
md 값이 8이 아니고 6이겠죠?

![image](https://user-images.githubusercontent.com/17868599/69925355-18913780-14f3-11ea-8d07-3c539c6fd029.png)

2019-12-03 12:20 UTC, KimJye commented on packages/client/views/Login/index.tsx
> +            <S.AuthenticateLink href="#">
혹시 이부분 저희 아직 api안됐나요?

2019-12-03 12:21 UTC, KimJye commented on packages/client/views/SignUp/index.tsx
> +            <S.Form onSubmit={() => null}>
의미하는 바가 무엇인가요?? 신기해요~

2019-12-03 12:22 UTC, KimJye approved these changes
고생하셨습니다

2019-12-03 12:23 UTC, riverandeye commented on packages/client/views/Login/index.tsx
> +            <S.AuthenticateLink href="#">
앗 잘은모르겠어요.. 로그인 테스트 할 때 반영하면 좋을것 같아요!

2019-12-03 12:43 UTC, Atercatus requested changes

2019-12-03 12:43 UTC, Atercatus commented on packages/client/views/Login/index.tsx
> +import Grid from '@material-ui/core/Grid';
import 라이브러리는 위로 올리고 코드는 아래로 내리고 사이에 빈 공백 넣어주세요

2019-12-03 12:43 UTC, Atercatus commented on packages/client/views/Login/styles.tsx
> +import MaterialGrid from '@material-ui/core/Grid';
여기도용

2019-12-03 12:43 UTC, Atercatus commented on packages/client/views/SignUp/index.tsx
> +            <S.Form onSubmit={() => null}>
웃지만 말고 지워 주세요 ㅎㅎ

2019-12-03 12:43 UTC, Atercatus commented on packages/client/views/SignUp/styles.tsx
> +import MaterialGrid from '@material-ui/core/Grid';
여기도용

2019-12-03 12:51 UTC, riverandeye commented on packages/client/views/SignUp/index.tsx
> +            <S.Form onSubmit={() => null}>
머지할떄 반영하겠습니다.

2019-12-03 12:53 UTC, Atercatus approved these changes

2019-12-03 13:09 UTC, alexKwonIsAwesome commented on packages/client/views/SignUp/index.tsx
> +            <S.Form onSubmit={() => null}>
12

2019-12-03 13:09 UTC, alexKwonIsAwesome commented on packages/client/views/SignUp/styles.tsx
> +  font-size: 3.2rem;
모바일에서 2.8이고, 데스크톱에서 3.2네요! 둘 다 적용해야 할것 같은데요?

2019-12-03 13:21 UTC, riverandeye commented on packages/client/views/SignUp/styles.tsx
> +  font-size: 3.2rem;
반영하였습니다!

2019-12-03 13:22 UTC, hyokualexkwon approved these changes

2019-12-03 13:42 UTC, merged